feat: 158 teacher teach edit student details
ocadotechnology/codeforlife-portal-react pull request #185
Opened 2023-10-02 22:35 UTC by KamilPawel

2023-10-05 12:52 UTC, cewei8483 requested changes
Please fix all the eslint errors (I didn't mark them all)

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-:-NfzqPHQ43IcgSVcFzic:btakkku)* status: 0 of 20 files reviewed, 16 unresolved discussions (waiting on @KamilPawel)

___
*[`backend/portal/views/teacher/dashboard.py` line 95 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-NfzsfZ_1VYNWnJBvhtC:-NfzsfZ_1VYNWnJBvhtD:b-gqukf) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/07eb112ae012dc7ed99463f7f701eb31437c3399/backend/portal/views/teacher/dashboard.py#L95)):*
> ```Python
> 
> 
> from django.core.exceptions import ObjectDoesNotExist
> ```

move import to top
___
*[`backend/portal/views/teacher/teach.py` line 616 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-Nfzt67jDSRUEscMhXP7:-Nfzt67jDSRUEscMhXP8:b-640uxv) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/07eb112ae012dc7ed99463f7f701eb31437c3399/backend/portal/views/teacher/teach.py#L616)):*
> ```Python
>                 "onboarding_done": True,
>                 "query_data": students_info,  # this field could be redundant
>                 # "class_url": request.build_absolute_uri(
> ```

delete if not used
___
*[`backend/portal/views/teacher/teach.py` line 977 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-NfztG8x0l5313juIZCl:-NfztG8x0l5313juIZCm:b-wgfvex) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/07eb112ae012dc7ed99463f7f701eb31437c3399/backend/portal/views/teacher/teach.py#L977)):*
> ```Python
> 
> # @csrf_exempt
> # def teacher_print_reminder_cards(request, access_code):
> ```

delete these comments if not used and not going to be referred
___
*[`backend/portal/views/teacher/teach.py` line 1088 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-NfzspWTACrB0ufstRF5:-NfzspWTACrB0ufstRF6:brganl2) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/07eb112ae012dc7ed99463f7f701eb31437c3399/backend/portal/views/teacher/teach.py#L1088)):*
> ```Python
> 
> 
> @csrf_exempt
> ```

remove this (and its import)
___
*[`frontend/src/components/form/StudentNameField.tsx` line 15 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-Nfzs2Fr5EizgVt0r5Qu:-Nfzs2Fr5EizgVt0r5Qv:b-r4jnd6) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/07eb112ae012dc7ed99463f7f701eb31437c3399/frontend/src/components/form/StudentNameField.tsx#L15)):*
> ```XML
>   helperText = 'Choose a name',
>   disabled = false,
>   style,
> ```

eslint
___
*[`frontend/src/features/newStudentsTable/NewStudentsTable.tsx` line 96 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-NfzsLJa80aga6901k37:-NfzsLJa80aga6901k38:b-r4jnd6) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/07eb112ae012dc7ed99463f7f701eb31437c3399/frontend/src/features/newStudentsTable/NewStudentsTable.tsx#L96)):*
> ```XML
>     }
>   };
>   const buttonStyles = isButtonBanner ? {
> ```

eslint
___
*[`frontend/src/features/newStudentsTable/NewStudentsTable.tsx` line 230 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-NfzsNBoEq3V8DmekIen:-NfzsNBoEq3V8DmekIeo:b2ni78k) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/07eb112ae012dc7ed99463f7f701eb31437c3399/frontend/src/features/newStudentsTable/NewStudentsTable.tsx#L230)):*
> ```XML
>                 <Typography marginRight={2}>Class link:</Typography>
>                 <Typography className="nowrap-ellipsis">
>                   {classLink} {'lol'}
> ```

lol
___
*[`frontend/src/pages/login/MyDocument.tsx` line 5 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-Nfzrr-h8iYWO_Ycr4ui:-Nfzrr-h8iYWO_Ycr4uj:b-r4jnd6) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/07eb112ae012dc7ed99463f7f701eb31437c3399/frontend/src/pages/login/MyDocument.tsx#L5)):*
> ```XML
> import CflLogo from '../../images/cfl_logo.png';
> ```

eslint
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx` line 85 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-NfzrfpV7QUsR1X8Mp8k:-NfzrfpV7QUsR1X8Mp8l:bd68b2r) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/07eb112ae012dc7ed99463f7f701eb31437c3399/frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx#L85)):*
> ```XML
>   };
> 
>   const { data, error, isLoading } = useGetStudentsByAccessCodeQuery({ accessCode });
> ```

should be disappeared after merging dev
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx` line 204 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-Nfzrejh-8hpBCsoWCTB:-Nfzrejh-8hpBCsoWCTC:b-r4jnd6) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/07eb112ae012dc7ed99463f7f701eb31437c3399/frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx#L204)):*
> ```XML
>   );
> };
> ```

eslint
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/student/editStudent/EditStudent.tsx` line 84 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-Nfzq6Ky5WgaOV3YraOJ:-Nfzq6Ky5WgaOV3YraOK:b-r4jnd6) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/07eb112ae012dc7ed99463f7f701eb31437c3399/frontend/src/pages/teacherDashboard/classes/editClass/student/editStudent/EditStudent.tsx#L84)):*
> ```XML
>   const initialValues: Values = {
>     password: '',
>     confirmPassword: '',
> ```

eslint
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/student/editStudent/EditStudent.tsx` line 92 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-Nfzq79O7dyk1kSJadOx:-Nfzq79O7dyk1kSJadOy:b-r4jnd6) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/07eb112ae012dc7ed99463f7f701eb31437c3399/frontend/src/pages/teacherDashboard/classes/editClass/student/editStudent/EditStudent.tsx#L92)):*
> ```XML
>       password: values.password,
>       studentId,
>       confirmPassword: values.confirmPassword,
> ```

eslint
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/student/editStudent/EditStudent.tsx` line 141 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-Nfzq9ch07bu88kSBmQr:-Nfzq9ch07bu88kSBmQs:bn3tz8m) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/07eb112ae012dc7ed99463f7f701eb31437c3399/frontend/src/pages/teacherDashboard/classes/editClass/student/editStudent/EditStudent.tsx#L141)):*
> ```XML
>           marginBottom={theme.spacing(11.5)}
>         >
>           Edit student details for Florian from class Class 1 ({accessCode})
> ```

replace Florian with student name
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/student/editStudent/UpdatedStudentCredentials.tsx` line 4 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-NfzqSri80K2sngSRVEK:-NfzqSri80K2sngSRVEL:b-r4jnd6) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/07eb112ae012dc7ed99463f7f701eb31437c3399/frontend/src/pages/teacherDashboard/classes/editClass/student/editStudent/UpdatedStudentCredentials.tsx#L4)):*
> ```XML
> import ClassCredentials from '../../../../../teacherOnboarding/ClassCredentials';
> import Page from 'codeforlife/lib/esm/components/page';
> import { Print } from '@mui/icons-material';
> ```

eslint
___
*[`frontend/src/pages/teacherOnboarding/ClassCredentials.tsx` line 42 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-NfzqqAI4Nlcd8N6QzEn:-NfzqqAI4Nlcd8N6QzEo:b-vudi2b) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/07eb112ae012dc7ed [...]

2023-10-05 16:36 UTC, cewei8483 requested changes
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185)* status: 0 of 25 files reviewed, 6 unresolved discussions (waiting on @KamilPawel)

___
*[`backend/portal/views/teacher/teach.py` line 586 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-Ng-fJbN0dR0n08favxS:-Ng-fJbN0dR0n08favxT:bb7mqkm) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/4439423061f193bf9139c9270f60d38549d99dc0/backend/portal/views/teacher/teach.py#L586)):*
> ```Python
>         domain = settings.SERVICE_DOMAIN
>         login_url = (
>             f"{protocol}://{domain}/api/u/{student.new_user.id}/{uuidstr}/"
> ```

port
___
*[`backend/portal/views/teacher/teach.py` line 1084 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-Ng-fa-o4mCYx6PrIsjC:-Ng-fa-o4mCYx6PrIsjD:b-735bk7) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/4439423061f193bf9139c9270f60d38549d99dc0/backend/portal/views/teacher/teach.py#L1084)):*
> ```Python
> 
> 
> def teacher_print_reminder_cards(request, access_code):
> ```

add `@login_required` 
___
*[`backend/portal/views/teacher/teach.py` line 1141 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-Ng-fNza2VTwvcqWPKR3:-Ng-fNza2VTwvcqWPKR4:bayl8qv) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/4439423061f193bf9139c9270f60d38549d99dc0/backend/portal/views/teacher/teach.py#L1141)):*
> ```Python
> 
> 
> def get_student_data(request):
> ```

comment this as well (it seems that it's only called by teacher_download_csv)
___
*[`frontend/src/pages/privacyNotice/ForAdults/HowWeUseInfo.tsx` line 16 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-Ng-fxAvBNDWGYaHeO3e:-Ng-fxAvBNDWGYaHeO3f:b-sfyspy) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/4439423061f193bf9139c9270f60d38549d99dc0/frontend/src/pages/privacyNotice/ForAdults/HowWeUseInfo.tsx#L16)):*
> ```XML
> const CustomTableRow: React.FC<{
>   left: string,
>   right: any;
> ```

remove the semicolon as it's not needed and not relevant to the task
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx` line 252 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-Ng-gDji5qdvvcQplX3R:-Ng-gDji5qdvvcQplX3S:b-1vxb4m) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/4439423061f193bf9139c9270f60d38549d99dc0/frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx#L252)):*
> ```XML
>   const studentData = data?.studentsPerAccessCode;
> ```

eslint :joy: 
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/student/editStudent/EditStudent.tsx` line 76 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-Ng-gHdZ41c-r0cnLiSg:-Ng-gHdZ41c-r0cnLiSh:b5wws46) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/4439423061f193bf9139c9270f60d38549d99dc0/frontend/src/pages/teacherDashboard/classes/editClass/student/editStudent/EditStudent.tsx#L76)):*
> ```XML
>   const [editStudentPassword] = useEditStudentPasswordMutation();
>   const location = useLocation();
>   console.log(location);
> ```

remove console.log


<!-- Sent from Reviewable.io -->

2023-10-05 16:37 UTC, cewei8483 reviewed
![image.png](https://files.reviewableusercontent.io/images/reviewable/65698922/u6tohi-prPEhAbmtZnun-ZoK/image.png)

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-:-Ng-gkTS0tENGHRTSOJp:bq2xczi)* status: 0 of 25 files reviewed, 6 unresolved discussions (waiting on @KamilPawel)



<!-- Sent from Reviewable.io -->

2023-10-06 08:59 UTC, cewei8483 requested changes
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185)* status: 0 of 25 files reviewed, 4 unresolved discussions (waiting on @KamilPawel)

___
*[`backend/portal/views/teacher/teach.py` line 1084 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-Ng-fa-o4mCYx6PrIsjC:-Ng3CS2U4ui27OKW51w5:b-505t8n) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/4439423061f193bf9139c9270f60d38549d99dc0/backend/portal/views/teacher/teach.py#L1084)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

add `@login_required`
</blockquote></details>

and `@user_passes_test(logged_in_as_teacher, login_url=reverse_lazy("teacher_login"))`


<!-- Sent from Reviewable.io -->

2023-10-06 09:03 UTC, cewei8483 requested changes
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185)* status: 0 of 25 files reviewed, 5 unresolved discussions (waiting on @KamilPawel)

___
*[`frontend/src/pages/teacherDashboard/classes/editClass/student/editStudent/EditStudent.tsx` line 98 at r7](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-Ng3DGYS6nKJCp5jH52J:-Ng3DGYS6nKJCp5jH52K:b8g9wc) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/183352e4eb1390c7957f69e6411fac40d6f1c44f/frontend/src/pages/teacherDashboard/classes/editClass/student/editStudent/EditStudent.tsx#L98)):*
> ```XML
>         const path = paths.teacher.dashboard.classes.editClass.updatedStudentCredentials._;
>         const { accessCode } = response;
>         console.log(response, path, accessCode);
> ```

remove `console.log`


<!-- Sent from Reviewable.io -->

2023-10-06 10:12 UTC, cewei8483 reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185)* status: 0 of 25 files reviewed, all discussions resolved

___
*[`backend/portal/views/teacher/teach.py` line 1084 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-Ng-fa-o4mCYx6PrIsjC:-Ng3SnDV0BULrIdxRWwI:b-qv1bu1) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/4439423061f193bf9139c9270f60d38549d99dc0/backend/portal/views/teacher/teach.py#L1084)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Shouldn't it be
```
@login_required(login_url=reverse_lazy("session-expired")) 
@user_passes_test( logged_in_as_teacher, login_url=reverse_lazy("session-expired") )
```
?


<!-- Sent from Reviewable.io -->

2023-10-06 10:19 UTC, KamilPawel reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185)* status: 0 of 25 files reviewed, all discussions resolved (waiting on @cewei8483)

___
*[`backend/portal/views/teacher/teach.py` line 1084 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-Ng-fa-o4mCYx6PrIsjC:-Ng3UXeHDXHnHfUzJaLV:b-whyneh) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/4439423061f193bf9139c9270f60d38549d99dc0/backend/portal/views/teacher/teach.py#L1084)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

Shouldn't it be
```
@login_required(login_url=reverse_lazy("session-expired")) 
@user_passes_test( logged_in_as_teacher, login_url=reverse_lazy("session-expired") )
```
?
</blockquote></details>

autocorrect on my end lol


<!-- Sent from Reviewable.io -->

2023-10-06 10:34 UTC, cewei8483 reviewed
Please fix the error on clicking back to class button :cry: 

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-:-Ng3YCWy8gI_xvtNeCxG:bcbxtc8)* status: 0 of 25 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-06 10:51 UTC, cewei8483 approved these changes
> Reviewed 3 of 20 files at r1, 5 of 9 files at r2, 7 of 12 files at r3, 2 of 5 files at r4, 1 of 1 files at r5, 3 of 5 files at r6, 1 of 3 files at r7, 2 of 3 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KamilPawel)



<!-- Sent from Reviewable.io -->

2023-10-23 17:40 UTC, faucomte97 requested changes
> Reviewed 1 of 20 files at r1, 2 of 9 files at r2, 1 of 12 files at r3, 1 of 1 files at r9, 2 of 3 files at r10, 1 of 4 files at r12, 4 of 14 files at r13, 1 of 7 files at r14, 16 of 29 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185)* status: 33 of 52 files reviewed, 14 unresolved discussions (waiting on @cewei8483 and @KamilPawel)

___
*[`backend/Pipfile` line 31 at r15](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-NhSWZf_8oRqffHCVgS4:-NhSWZf_8oRqffHCVgS5:blvpx6l) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/548e50811dec2f8effc020ec6cee1fad023b2433/backend/Pipfile#L31)):*
> ```TOML
> google-cloud-container = "==2.3.0"
> "django-anymail[amazon_ses]" = "==7.0.*"
> codeforlife = {ref = "158-teacher-teach-edit-student-details", git = "https://github.com/ocadotechnology/codeforlife-package-python.git"}
> ```

Reminder of branch install
___
*[`backend/portal/urls/teacher/dashboard.py` line 95 at r15](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-NhSXQ-b4Cz3jmBYEN2B:-NhSXQ-c9y2COY5lpZxT:b-rhmpps) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/548e50811dec2f8effc020ec6cee1fad023b2433/backend/portal/urls/teacher/dashboard.py#L95)):*
> ```Python
>         r"^class/student/(?P<student_id>[0-9]+)/$",
>         get_student_details,
>         name="get_student_details",
> ```

Please double check whether these two endpoints are needed in this file (they don't seem like teacher dashboard features to me)



_Code quote:_
```Python
    re_path(
        rf"^class/students/(?P<access_code>{ACCESS_CODE_REGEX})/$",
        get_students_from_access_code,
        name="get_students_from_acccess_code",
    ),
    re_path(
        r"^class/student/(?P<student_id>[0-9]+)/$",
        get_student_details,
        name="get_student_details",
```
___
*[`backend/portal/views/school.py` line 7 at r15](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-NhSXjNF5TcF54S4h24n:-NhSXjNF5TcF54S4h24o:b-h9xcl5) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/548e50811dec2f8effc020ec6cee1fad023b2433/backend/portal/views/school.py#L7)):*
> ```Python
> 
> class SchoolViewSet(_SchoolViewSet):
>     http_method_names = ["get", "post", "patch", "delete"]
> ```

Users don't actually have the functionality to delete schools yet.
Schools as of now never get deleted unless we do so in the django admin.
___
*[`backend/portal/views/teacher/dashboard.py` line 99 at r15](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-NhSYATZDbp6wz3vf5HD:-NhSYATZDbp6wz3vf5HE:b-himqaj) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/548e50811dec2f8effc020ec6cee1fad023b2433/backend/portal/views/teacher/dashboard.py#L99)):*
> ```Python
> 
> 
> def get_student_details(request, student_id):
> ```

Just questioning again why this endpoint and the one above are here in the `dashboard` file. Seems like class specific endpoints to me.
Now that I'm typing this I'm thinking this endpoint might be needed in the dashboard for the independent student join requests, but still not sure about the one above.
___
*[`backend/portal/views/teacher/teach.py` line 535 at r15](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-NhSYpeTCwxzrLTIkk85:-NhSYpeTCwxzrLTIkk86:b-clchna) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/548e50811dec2f8effc020ec6cee1fad023b2433/backend/portal/views/teacher/teach.py#L535)):*
> ```Python
> 
>     if request.method == "POST":
>         if "name" in request.POST:
> ```

Why replace the old check with this one?
___
*[`backend/portal/views/teacher/teach.py` line 568 at r15](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-NhSZVAe9GTuwybC9YCN:-NhSZVAe9GTuwybC9YCO:bfer8ma) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/548e50811dec2f8effc020ec6cee1fad023b2433/backend/portal/views/teacher/teach.py#L568)):*
> ```Python
>         return JsonResponse(
>             {
>                 "message": "Your details were not updated due to incorrect details"
> ```

I can't think of a case where this would happen? (basically do we need that piece of code?)
___
*[`backend/portal/views/teacher/teach.py` line 939 at r15](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-NhS_KSG5LarF1zbtgGv:-NhS_KSG5LarF1zbtgGw:b-dxi3ob) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/548e50811dec2f8effc020ec6cee1fad023b2433/backend/portal/views/teacher/teach.py#L939)):*
> ```Python
> # to fix the dictionary issue, feel free to use it and
> # delete this method
> def expand_key(dictionary):
> ```

Not sure what the issue in question here is, also not sure if it's worth being more specific.
___
*[`backend/portal/views/teacher/teach.py` line 1113 at r15](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-NhS_cM84Je430oGT22v:-NhS_cM9ArqDNa-lHXn0:bt4ypbx) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/548e50811dec2f8effc020ec6cee1fad023b2433/backend/portal/views/teacher/teach.py#L1113)):*
> ```Python
> 
> 
> # TODO: before deploying make sure the count_student_details_click is implemented
> ```

Not too sure what is going on in this file. Not yet able to tell which parts are implemented or not (I do have a lot of the review left)
___
*[`frontend/src/app/api/klass.ts` line 111 at r15](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-NhSaX8VE7y8VhN5_p3W:-NhSaX8VE7y8VhN5_p3X:b4o4qw8) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/548e50811dec2f8effc020ec6cee1fad023b2433/frontend/src/app/api/klass.ts#L111)):*
> ```XML
>       }),
>       invalidatesTags: (result, error, { accessCode }) => !error
>         ? [{ type: 'school', id: accessCode }]
> ```

why type school? Should be class no?
___
*[`frontend/src/app/api/school.ts` line 25 at r15](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-NhSamIv50306OTYGD6A:-NhSamIv50306OTYGD6B:b2i3x28) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/548e50811dec2f8effc020ec6cee1fad023b2433/frontend/src/app/api/school.ts#L25)):*
> ```XML
>     country: string;
>     county: null | string;
>     isActive?: boolean;
> ```

Not too sure why some of these are optional and others aren't. County could very well be optional imo.
I think there were similar inconsistencies in the Class model too.



_Code quote:_
```XML
    county: null | string;
    isActive?: boolean;
```
___
*[`frontend/src/app/api/user.ts` line 27 at r15](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-NhSbLJK7KwzxO39JcC5:-NhSbLJK7KwzxO39JcC6:b-miwplh) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/548e50811dec2f8effc020ec6cee1fad023b2433/frontend/src/app/api/user.ts#L27)):*
> ```XML
>     lastName: string;
>     email: string;
>     password: null | string;
> ```

Didn't you say the password field should be writeOnly?
___
*[`frontend/src/app/api/user.ts` line 124 at r15](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-NhSb_vXEVbrg5gkYse8:-NhSb_vXEVbrg5gkYse9:b-y74n3o) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/548e50811dec2f8effc020ec6cee1fad023b2433/frontend/src/app/api/user.ts#L124)):*
> ```XML
>         : []
>     }),
>     updateUser: build.mutation<
> ```

no BulkUpdateUsers?
___
*[`frontend/src/app/api/user.ts` line 140 at r15](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-NhSbXxPEvlL-_VZTDS3:-NhSbXxPEvlL-_VZTDS4:b-6yps2j) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/548e50811dec2f8effc020ec6cee1fad023b2433/frontend/src/app/api/user.ts#L1 [...]

2023-10-23 20:08 UTC, faucomte97 requested changes
> Reviewed 1 of 9 files at r2, 1 of 5 files at r4, 5 of 14 files at r13, 1 of 7 files at r14, 13 of 29 files at r15.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185)* status: all files reviewed, 22 unresolved discussions (waiting on @KamilPawel)

___
*[`frontend/src/app/api/teacher/teach.ts` line 102 at r15](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-NhT5eifEb1iEZLdxkkL:-NhT5eifEb1iEZLdxkkM:b-h2ocvn) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/548e50811dec2f8effc020ec6cee1fad023b2433/frontend/src/app/api/teacher/teach.ts#L102)):*
> ```XML
>       query: ({ studentId, password, confirmPassword }) => ({
>         url: `teach/student/edit/${studentId}`,
>         method: 'POST',
> ```

Why is this POST and not PATCH? Same for the update class mutation above.
___
*[`frontend/src/app/api/teacher/teach.ts` line 118 at r15](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-NhT5l0j-J7WbawS5FDF:-NhT5l0j-J7WbawS5FDG:b-gsac8b) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/548e50811dec2f8effc020ec6cee1fad023b2433/frontend/src/app/api/teacher/teach.ts#L118)):*
> ```XML
>       query: ({ studentId, name }) => ({
>         url: `teach/student/edit/${studentId}`,
>         method: 'POST',
> ```

Same question here
___
*[`frontend/src/app/api/teacher/teach.ts` line 132 at r15](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-NhT5u9j-si2W-OpOK1X:-NhT5u9j-si2W-OpOK1Y:b-y1fp95) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/548e50811dec2f8effc020ec6cee1fad023b2433/frontend/src/app/api/teacher/teach.ts#L132)):*
> ```XML
>       query: ({ accessCode }) => ({
>         url: `teach/class/delete/${accessCode}`,
>         method: 'POST',
> ```

why is this a POST and not a DELETE?
___
*[`frontend/src/app/api/teacher/teach.ts` line 145 at r15](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-NhT6349A_TDpDiItY9g:-NhT6349A_TDpDiItY9h:bg50bh4) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/548e50811dec2f8effc020ec6cee1fad023b2433/frontend/src/app/api/teacher/teach.ts#L145)):*
> ```XML
>       query: (body) => ({
>         url: 'teach/move_class/',
>         method: 'POST',
> ```

Same here - shouldn't this be a PATCH? :confused: 
___
*[`frontend/src/app/api/teacher/teach.ts` line 159 at r15](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-NhT66w9-IFpm-XzVNbW:-NhT66w9-IFpm-XzVNbX:b-1boefp) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/548e50811dec2f8effc020ec6cee1fad023b2433/frontend/src/app/api/teacher/teach.ts#L159)):*
> ```XML
>       query: ({ accessCode, data }) => ({
>         url: `teach/onboarding-class/${accessCode}/print-reminder-cards/`,
>         method: 'POST',
> ```

Post or get?
___
*[`frontend/src/pages/teacherDashboard/YourSchool.tsx` line 201 at r15](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-NhT6uohAuamgTmueMOU:-NhT6uoiECofMqSuAsu1:b-9k9329) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/548e50811dec2f8effc020ec6cee1fad023b2433/frontend/src/pages/teacherDashboard/YourSchool.tsx#L201)):*
> ```XML
>   const schoolPostcode = schoolData.postcode;
>   const schoolCountry = schoolData.country;
>   const [updateSchool] = useOldUpdateSchoolMutation();
> ```

Can we replace / remove this?
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/student/editStudent/StudentCredentials.tsx` line 66 at r15](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-NhT81KS0Mr8xXk0t5LQ:-NhT81KS0Mr8xXk0t5LR:b-66qnc6) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/548e50811dec2f8effc020ec6cee1fad023b2433/frontend/src/pages/teacherDashboard/classes/editClass/student/editStudent/StudentCredentials.tsx#L66)):*
> ```XML
>           header='Class and class access code:'
>         />
>         <Page.Notification>
> ```

Does this notification have the right icon like we discussed?
___
*[`frontend/src/pages/teacherOnboarding/TeacherOnboarding.tsx` line 103 at r15](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-NhT8c7V5_HHXgSM4SKD:-NhT8c7V5_HHXgSM4SKE:b92lb9f) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/548e50811dec2f8effc020ec6cee1fad023b2433/frontend/src/pages/teacherOnboarding/TeacherOnboarding.tsx#L103)):*
> ```XML
>               <AddStudentsForm
>                 key={generateKey(2)}
>                 // classId={activeStep.classId as number}
> ```

please remove if not needed then


<!-- Sent from Reviewable.io -->

2023-10-24 10:49 UTC, SKairinos reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-:-NhQplbg0MFPq-12-0WE:bnfp4nl)* status: 51 of 52 files reviewed, 22 unresolved discussions (waiting on @faucomte97 and @KamilPawel)



<!-- Sent from Reviewable.io -->

2023-10-24 10:49 UTC, SKairinos reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185)* status: 51 of 52 files reviewed, 22 unresolved discussions (waiting on @faucomte97 and @KamilPawel)

___
*[`frontend/src/app/api/klass.ts` line 111 at r15](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-NhSaX8VE7y8VhN5_p3W:-NhWINyNCbnYi1MPT_Fz:bb7f2mf) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/548e50811dec2f8effc020ec6cee1fad023b2433/frontend/src/app/api/klass.ts#L111)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

why type school? Should be class no?
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-10-24 14:03 UTC, SKairinos reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185)* status: 47 of 52 files reviewed, 22 unresolved discussions (waiting on @faucomte97 and @KamilPawel)

___
*[`backend/portal/urls/teacher/dashboard.py` line 95 at r15](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-NhSXQ-b4Cz3jmBYEN2B:-NhWum0nDWAVHhM9OaTS:b1oco14) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/548e50811dec2f8effc020ec6cee1fad023b2433/backend/portal/urls/teacher/dashboard.py#L95)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Please double check whether these two endpoints are needed in this file (they don't seem like teacher dashboard features to me)
</blockquote></details>

will address in another task
___
*[`frontend/src/app/api/user.ts` line 124 at r15](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-NhSb_vXEVbrg5gkYse8:-NhWzVaUA1cPDeOz2Iic:bb7f2mf) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/548e50811dec2f8effc020ec6cee1fad023b2433/frontend/src/app/api/user.ts#L124)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

no BulkUpdateUsers?
</blockquote></details>

done
___
*[`frontend/src/app/api/user.ts` line 140 at r15](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185#-NhSbXxPEvlL-_VZTDS3:-NhWzWoP5CXByzAYbEas:bb7f2mf) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/548e50811dec2f8effc020ec6cee1fad023b2433/frontend/src/app/api/user.ts#L140)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

no BulkDestroyUsers?
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-10-24 14:34 UTC, faucomte97 reviewed
> Reviewed 1 of 3 files at r8, 1 of 1 files at r16, 3 of 4 files at r17, 9 of 9 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KamilPawel)



<!-- Sent from Reviewable.io -->

2023-10-24 14:35 UTC, faucomte97 approved these changes
> Reviewed 1 of 12 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/185)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KamilPawel)



<!-- Sent from Reviewable.io -->

2023-10-24 14:35 UTC, merged