Reset password endpoints
ocadotechnology/codeforlife-portal-react pull request #258
Opened 2024-01-29 18:34 UTC by faucomte97

2024-02-01 16:08 UTC, SKairinos requested changes
> Reviewed 5 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258)* status: 5 of 10 files reviewed, 22 unresolved discussions (waiting on @faucomte97)

___
*[`backend/Pipfile` line 31 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-Np_IvnD7LywuqoSVrr9:-Np_IvnD7LywuqoSVrrA:b-5po1yl) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3fc09f254312fba4b9cd4493fec709df0c61932b/backend/Pipfile#L31)):*
> ```TOML
> google-cloud-container = "==2.3.0"
> # "django-anymail[amazon_ses]" = "==7.0.*"
> codeforlife = {ref = "v0.12.0", git = "https://github.com/ocadotechnology/codeforlife-package-python.git"}
> ```

install v0.12.1 after you approve and merge my PR.
https://github.com/ocadotechnology/codeforlife-package-python/pull/68
___
*[`backend/api/serializers/user.py` line 11 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-NpZqOT6419STGHISbef:-NpZqOT6419STGHISbeg:b-n9glo) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3fc09f254312fba4b9cd4493fec709df0c61932b/backend/api/serializers/user.py#L11)):*
> ```Python
> 
> from codeforlife.serializers import ModelListSerializer, ModelSerializer
> from codeforlife.user.auth.password_validators import (
> ```

Read this: https://docs.djangoproject.com/en/5.0/topics/auth/passwords/#integrating-validation
remove the imports and replace with
`from django.contrib.auth.password_validation import validate_password as _validate_password`
___
*[`backend/api/serializers/user.py` line 134 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-Np_Q2iy2e-JzhjXq-T1:-Np_Q2iy2e-JzhjXq-T2:b-hns5dj) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3fc09f254312fba4b9cd4493fec709df0c61932b/backend/api/serializers/user.py#L134)):*
> ```Python
> 
>     def validate(self, attrs):
>         # TODO: make current password required when changing self-profile.
> ```

add this for later

if self.view.action != "reset-password":
    pass # TODO: make current password required when changing self-profile.


this is necessary because we normally require current password when changing the user's profile EXCEPT when we are resetting their password. 
___
*[`backend/api/serializers/user.py` line 155 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-Np_OgrGDrkBoRIS981a:-Np_OgrGDrkBoRIS981b:bne73hn) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3fc09f254312fba4b9cd4493fec709df0c61932b/backend/api/serializers/user.py#L155)):*
> ```Python
> 
> # pylint: disable-next=missing-class-docstring
> class PasswordResetSerializer(ModelSerializer[User]):
> ```

We need to remove this serializer and merge it's logic into UserSerializer above.

This serializer is unnecessary since we're taking about updating a user field.

Also, updating the user's password is logic we will want to reuse!
___
*[`backend/api/serializers/user.py` line 161 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-Np_PBjx-d3pgyw6kkvH:-Np_PBjx-d3pgyw6kkvI:b96oic8) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3fc09f254312fba4b9cd4493fec709df0c61932b/backend/api/serializers/user.py#L161)):*
> ```Python
>         extra_kwargs = {"password": {"write_only": True}}
> 
>     def validate_password(self, value: str):
> ```

move to UserSerializer
___
*[`backend/api/serializers/user.py` line 166 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-NpZqIze0glJOP-AhXu7:-NpZqIzf7V2Lh9O-CtRg:b-pxkoey) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3fc09f254312fba4b9cd4493fec709df0c61932b/backend/api/serializers/user.py#L166)):*
> ```Python
>         :param value: the new password
>         """
>         user = getattr(self, "instance", None)
> ```

Read this: https://docs.djangoproject.com/en/5.0/topics/auth/passwords/#integrating-validation
Replace with `_validate_password(value, self.instance)`

Also your previous approach is dangerous because you're not calling the other password validators (e.g. common password validator)
___
*[`backend/api/serializers/user.py` line 166 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-NpZrWhA51A_6_tB7pqm:-NpZrWhA51A_6_tB7pqn:b9g7r29) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3fc09f254312fba4b9cd4493fec709df0c61932b/backend/api/serializers/user.py#L166)):*
> ```Python
>         :param value: the new password
>         """
>         user = getattr(self, "instance", None)
> ```

user = t.cast(User, self.instance)

We can guarantee that instance will be a user since you set/pass it in the view.
___
*[`backend/api/serializers/user.py` line 176 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-Np_PZ9_2OPJg8KRyhev:-Np_PZ9_2OPJg8KRyhew:b-3x51vm) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3fc09f254312fba4b9cd4493fec709df0c61932b/backend/api/serializers/user.py#L176)):*
> ```Python
>         return value
> 
>     def update(self, instance, validated_data):
> ```

move to UserSerializer BUT update code to:

password = validated_data.get("password")
if password is not None:
    instance.set_password(password)


this is necessary because we allow partial updates
___
*[`backend/api/views/user.py` line 35 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-NpZyHb-CFr7eO39i8bW:-NpZyHb-CFr7eO39i8bX:b-ij988q) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3fc09f254312fba4b9cd4493fec709df0c61932b/backend/api/views/user.py#L35)):*
> ```Python
> 
>     @action(detail=False, methods=["post"], permission_classes=[AllowAny])
>     def is_unique_email(self, request):
> ```

add type hints.

for request, please use:
`from codeforlife.request import Request`
___
*[`backend/api/views/user.py` line 43 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-Np_LP5YEk2vng9rRwdS:-Np_LP5YEk2vng9rRwdT:b-t5gipv) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3fc09f254312fba4b9cd4493fec709df0c61932b/backend/api/views/user.py#L43)):*
> ```Python
>         )
> 
>     @action(
> ```

should be
`@action(
detail=True,
methods=["patch"],
url_path="reset-password/(?P<token>.+)",
permission_classes=[AllowAny],
)`

we *do* want this action to be for a specific, known user. 

also, we don't need to support HTTP GET. We should do it all in a PATCH. on PATCH request:
1. get the user `user = get_object()`
2. check the token belongs to the user
3. get the serializer `serializer = get_serializer(user, data=rquest.data)`
4. `serializer.is_valid(raise_exception=True)`
5. `serializer.save()`
6. `return Response()`
___
*[`backend/api/views/user.py` line 49 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-NpZy4xlBYufaGgg1zOt:-NpZy4xlBYufaGgg1zOu:b-q8gwfw) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3fc09f254312fba4b9cd4493fec709df0c61932b/backend/api/views/user.py#L49)):*
> ```Python
>         permission_classes=[AllowAny],
>     )
>     def reset_password(self, request, uidb64=None, token=None):
> ```

add type hints.

for request, please use:
`from codeforlife.request import Request`

also replace uid64 with pk
___
*[`backend/api/views/user.py` line 49 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-NpZyJe7BhIs9c9vQhK0:-NpZyJe7BhIs9c9vQhK1:b-wowc4w) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3fc09f254312fba4b9cd4493fec709df0c61932b/backend/api/views/user.py#L49)):*
> ```Python
>         permission_classes=[AllowAny],
>     )
>     def reset_password(self, request, uidb64=None, token=None):
> ```

add functi [...]

2024-02-01 16:17 UTC, SKairinos requested changes
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258)* status: 5 of 10 files reviewed, 21 unresolved discussions (waiting on @faucomte97)

___
*[`backend/api/serializers/user.py` line 166 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-NpZqIze0glJOP-AhXu7:-Np_SLVT7mzd6FVICMau:b24o4o) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3fc09f254312fba4b9cd4493fec709df0c61932b/backend/api/serializers/user.py#L166)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

Read this: https://docs.djangoproject.com/en/5.0/topics/auth/passwords/#integrating-validation
Replace with `_validate_password(value, self.instance)`

Also your previous approach is dangerous because you're not calling the other password validators (e.g. common password validator)
</blockquote></details>

side note: I fixed the type hint for `self.instance`. It will now always have the type of the model (it's not optional and not a sequence).


<!-- Sent from Reviewable.io -->

2024-02-02 14:24 UTC, SKairinos requested changes
> Reviewed 4 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258)* status: 8 of 11 files reviewed, 7 unresolved discussions (waiting on @faucomte97)

___
*[`backend/api/serializers/user.py` line 148 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-Npe8Xdh0Kj24ZeYBD_t:-Npe8Xdh0Kj24ZeYBD_u:b-c7tqo5) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/73403654b056998f4e8f6ac977c2912776f5588d/backend/api/serializers/user.py#L148)):*
> ```Python
> 
>     def update(self, instance, validated_data):
>         password = validated_data["password"]
> ```

don't index the dict because we allow partial updates, "password" may not be in validated_data.

`validated_data.get("password")`
___
*[`backend/api/serializers/user.py` line 152 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-Npe8lzhB6uJGzAZLLK9:-Npe8lzhB6uJGzAZLLKA:b-8alqrp) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/73403654b056998f4e8f6ac977c2912776f5588d/backend/api/serializers/user.py#L152)):*
> ```Python
>         if password is not None:
>             instance.set_password(password)
>             instance.save()
> ```

put instance.save() outside the if. we should always save at the end of update(), regardless of what fields were updated.
___
*[`backend/api/views/user.py` line 13 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-NpeBLuX3u9_k4IP0RNE:-NpeBLuY4-JIkO4gZTCs:b-m1rs14) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/73403654b056998f4e8f6ac977c2912776f5588d/backend/api/views/user.py#L13)):*
> ```Python
> from codeforlife.user.views import UserViewSet as _UserViewSet
> from django.contrib.auth.tokens import default_token_generator
> from django.core.exceptions import ObjectDoesNotExist
> ```

remove this import. included by default in every model. for example:

`User.DoesNotExist`
___
*[`backend/api/views/user.py` line 49 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-Npe9clC20TQlaQqEvuA:-Npe9clC20TQlaQqEvuB:b4tilrj) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/73403654b056998f4e8f6ac977c2912776f5588d/backend/api/views/user.py#L49)):*
> ```Python
>     )
>     def reset_password(
>         self, request: Request, pk: int = None, token: str = None
> ```

pk is actually str since all url params are strings.

detail=True basically adds "pk" to the start of our path so the full path is

"<pk>/reset-password/<token>"
___
*[`backend/api/views/user.py` line 59 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-NpeABXk1CDEyJdNw5bH:-NpeABXk1CDEyJdNw5bI:bh8w2ew) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/73403654b056998f4e8f6ac977c2912776f5588d/backend/api/views/user.py#L59)):*
> ```Python
>         """
>         try:
>             user = User.objects.get(pk=pk)
> ```

`user = User.objects.get(pk=int(pk))` 

pk is a str at this point
___
*[`backend/api/views/user.py` line 60 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-Npe9wfS7KkWHZ2mssdv:-Npe9wfS7KkWHZ2mssdw:b3xtk10) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/73403654b056998f4e8f6ac977c2912776f5588d/backend/api/views/user.py#L60)):*
> ```Python
>         try:
>             user = User.objects.get(pk=pk)
>         except (TypeError, ValueError, OverflowError, ObjectDoesNotExist):
> ```

Only need to catch the following errors

`except (ValueError, User.DoesNotExist):`

ValueError in case the pk is not the string representation of an int.
___
*[`backend/api/views/user.py` line 97 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-NpeBHQG78IK-bQBm5D-:-NpeBHQG78IK-bQBm5D0:bz4xuje) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/73403654b056998f4e8f6ac977c2912776f5588d/backend/api/views/user.py#L97)):*
> ```Python
>         try:
>             user = User.objects.get(email__iexact=email)
>         except ObjectDoesNotExist:
> ```

`except User.DoesNotExist:`


<!-- Sent from Reviewable.io -->

2024-02-02 14:53 UTC, SKairinos requested changes
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258)* status: 8 of 11 files reviewed, 18 unresolved discussions (waiting on @faucomte97)

___
*[`backend/api/tests/views/test_user.py` line 31 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-NpeCv5l-YXJ-LZiAkoD:-NpeCv5l-YXJ-LZiAkoE:bto0up7) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/73403654b056998f4e8f6ac977c2912776f5588d/backend/api/tests/views/test_user.py#L31)):*
> ```Python
>     fixtures = ["independent", "non_school_teacher"]
> 
>     teacher_email = "teacher@noschool.com"
> ```

rename to non_school_teacher_email for readability
___
*[`backend/api/tests/views/test_user.py` line 94 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-NpeEEaSDp610BRH2yJt:-NpeEEaSDp610BRH2yJu:br0a4sm) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/73403654b056998f4e8f6ac977c2912776f5588d/backend/api/tests/views/test_user.py#L94)):*
> ```Python
>         viewname = self.client.reverse("request-password-reset")
> 
>         response = self.client.post(
> ```

normally we don't need to manually assert the status_code because I have written some in-between code that will always assert `200 <= status_code < 300`.

However, in this case, we have a special case that we must always return 200 specifically so we need to set `status_code_assertion=status.HTTP_200_OK`
___
*[`backend/api/tests/views/test_user.py` line 123 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-NpeFS7HB_qrugWvGfo7:-NpeFS7HB_qrugWvGfo8:b-2n0xsx) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/73403654b056998f4e8f6ac977c2912776f5588d/backend/api/tests/views/test_user.py#L123)):*
> ```Python
>     def test_reset_password__invalid_pk(self):
>         """Check reset password raises 400 on GET with invalid pk"""
>         response = self._request_reset_password_response(self.teacher_email)
> ```

for each of the test_reset_password UTs, don't use self._request_reset_password_response to setup the test.

we shouldn't do more than one HTTP call per UT.

This is because this data won't be returned in the final implementation of the endpoint (when it actually sends the email).

Instead, you should:

1.  delete this helper function and override `def setUp`.
2. in setUp, get the user
3. at the top, import default_token_generator
4.  in setUp, create a token for the user
5. `.reverse("reset-password", kwargs={"pk": self.user.pk, "token": self.token})`
___
*[`backend/api/tests/views/test_user.py` line 147 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-NpeH7gC5sQNW8LBekL8:-NpeH7gC5sQNW8LBekL9:b94exup) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/73403654b056998f4e8f6ac977c2912776f5588d/backend/api/tests/views/test_user.py#L147)):*
> ```Python
>         )
> 
>         invalid_token_response = self.client.get(
> ```

rename to just response after you remove the first request. do this for each test case
___
*[`backend/api/tests/views/test_user.py` line 160 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-NpeHfVO9h-BLx-f82DD:-NpeHfVO9h-BLx-f82DE:bou21f9) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/73403654b056998f4e8f6ac977c2912776f5588d/backend/api/tests/views/test_user.py#L160)):*
> ```Python
>         reset_password_url = response.data["reset_password_url"]
> 
>         self.client.get(reset_password_url)
> ```

remove the get from here and create dedciated test for it.

we shouldn't do more than one HTTP call per UT.
___
*[`backend/api/tests/views/test_user.py` line 162 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-NpeIhy24fGevAVcns-E:-NpeIhy24fGevAVcns-F:be3xqza) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/73403654b056998f4e8f6ac977c2912776f5588d/backend/api/tests/views/test_user.py#L162)):*
> ```Python
>         self.client.get(reset_password_url)
> 
>         # Test reset-password PATCH for teacher
> ```

remove comment. repeating docstring
___
*[`backend/api/tests/views/test_user.py` line 164 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-NpeIKku20PUKRLKAfAi:-NpeIKku20PUKRLKAfAj:b-ne61ja) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/73403654b056998f4e8f6ac977c2912776f5588d/backend/api/tests/views/test_user.py#L164)):*
> ```Python
>         # Test reset-password PATCH for teacher
>         self.client.patch(reset_password_url, data={"password": "N3wPassword!"})
>         self.client.login(email=self.teacher_email, password="N3wPassword!")
> ```

`user = self.client.login(...)`

you then need to assert that user is not None  
___
*[`backend/api/tests/views/test_user.py` line 165 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-NpeIHq_69S3xTFbZYvn:-NpeIHq_69S3xTFbZYvo:b80jsdr) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/73403654b056998f4e8f6ac977c2912776f5588d/backend/api/tests/views/test_user.py#L165)):*
> ```Python
>         self.client.patch(reset_password_url, data={"password": "N3wPassword!"})
>         self.client.login(email=self.teacher_email, password="N3wPassword!")
>         self.client.logout()
> ```

no need to logout.
___
*[`backend/api/tests/views/test_user.py` line 172 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-NpeHplx7NvGLxVs6Oc1:-NpeHplx7NvGLxVs6Oc2:bou21f9) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/73403654b056998f4e8f6ac977c2912776f5588d/backend/api/tests/views/test_user.py#L172)):*
> ```Python
>         reset_password_url = response.data["reset_password_url"]
> 
>         self.client.get(reset_password_url)
> ```

remove the get from here and create dedciated test for it.

we shouldn't do more than one HTTP call per UT.
___
*[`backend/api/tests/views/test_user.py` line 174 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-NpeIeAn1MzsYzs6dvn1:-NpeIeAn1MzsYzs6dvn2:be3xqza) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/73403654b056998f4e8f6ac977c2912776f5588d/backend/api/tests/views/test_user.py#L174)):*
> ```Python
>         self.client.get(reset_password_url)
> 
>         # Test reset-password PATCH for indy
> ```

remove comment. repeating docstring
___
*[`backend/api/tests/views/test_user.py` line 176 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-NpeIba4AKZdhq3QOVKH:-NpeIba4AKZdhq3QOVKI:b-ne61ja) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/73403654b056998f4e8f6ac977c2912776f5588d/backend/api/tests/views/test_user.py#L176)):*
> ```Python
>         # Test reset-password PATCH for indy
>         self.client.patch(reset_password_url, data={"password": "N3wPassword"})
>         self.client.login(email=self.indy_email, password="N3wPassword")
> ```

`user = self.client.login(...)`

you then need to assert that user is not None  


<!-- Sent from Reviewable.io -->

2024-02-02 14:54 UTC, SKairinos commented
*[`backend/api/views/user.py` line 49 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-Npe9clC20TQlaQqEvuA:-NpeIwGO3UB-ZVLwg_0H:bvbvkst) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/73403654b056998f4e8f6ac977c2912776f5588d/backend/api/views/user.py#L49)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

pk is actually str since all url params are strings.

detail=True basically adds "pk" to the start of our path so the full path is

"<pk>/reset-password/<token>"
</blockquote></details>

sorry, I meant

"(pk)/reset-password/(token)"


<!-- Sent from Reviewable.io -->

2024-02-02 15:35 UTC, SKairinos requested changes
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258)* status: 8 of 11 files reviewed, 20 unresolved discussions (waiting on @faucomte97)

___
*[`backend/api/serializers/user.py` line 142 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-NpeSKNr-rks31BATCeR:-NpeSKNr-rks31BATCeS:b-jcmg9n) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/73403654b056998f4e8f6ac977c2912776f5588d/backend/api/serializers/user.py#L142)):*
> ```Python
>         """
>         Validate the new password depending on user type.
>         :param value: the new password
> ```

we need to agree on param convention.
___
*[`backend/api/tests/views/test_user.py` line 112 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-NpeSOHF064l2346VreE:-NpeSOHF064l2346VreF:b-snk3id) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/73403654b056998f4e8f6ac977c2912776f5588d/backend/api/tests/views/test_user.py#L112)):*
> ```Python
>     def test_request_password_reset__valid_email(self):
>         """
>         Check request password reset generates reset password URL for valid
> ```

remove "check" pretext from each UT.


<!-- Sent from Reviewable.io -->

2024-02-02 18:06 UTC, faucomte97 reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258)* status: 8 of 11 files reviewed, 20 unresolved discussions (waiting on @faucomte97 and @SKairinos)

___
*[`backend/api/serializers/user.py` line 142 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-NpeSKNr-rks31BATCeR:-NpevMqP51eJeGh-8ZWF:b-qjpbyu) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/73403654b056998f4e8f6ac977c2912776f5588d/backend/api/serializers/user.py#L142)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

we need to agree on param convention.
</blockquote></details>

Will investigate stache
___
*[`backend/api/serializers/user.py` line 148 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-Npe8Xdh0Kj24ZeYBD_t:-NpeZ4Cb8GAIv5JHbnl9:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/73403654b056998f4e8f6ac977c2912776f5588d/backend/api/serializers/user.py#L148)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

don't index the dict because we allow partial updates, "password" may not be in validated_data.

`validated_data.get("password")`
</blockquote></details>

Done.
___
*[`backend/api/serializers/user.py` line 152 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-Npe8lzhB6uJGzAZLLK9:-NpeZ9azAGTzM5YDCTyj:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/73403654b056998f4e8f6ac977c2912776f5588d/backend/api/serializers/user.py#L152)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

put instance.save() outside the if. we should always save at the end of update(), regardless of what fields were updated.
</blockquote></details>

Done.
___
*[`backend/api/tests/views/test_user.py` line 31 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-NpeCv5l-YXJ-LZiAkoD:-NpevQj51rBwQPWUYbd-:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/73403654b056998f4e8f6ac977c2912776f5588d/backend/api/tests/views/test_user.py#L31)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

rename to non_school_teacher_email for readability
</blockquote></details>

Done.
___
*[`backend/api/tests/views/test_user.py` line 94 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-NpeEEaSDp610BRH2yJt:-NpevbYI6J6T19DTGYvf:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/73403654b056998f4e8f6ac977c2912776f5588d/backend/api/tests/views/test_user.py#L94)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

normally we don't need to manually assert the status_code because I have written some in-between code that will always assert `200 <= status_code < 300`.

However, in this case, we have a special case that we must always return 200 specifically so we need to set `status_code_assertion=status.HTTP_200_OK`
</blockquote></details>

Done.
___
*[`backend/api/tests/views/test_user.py` line 112 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-NpeSOHF064l2346VreE:-Npevmol9Q7iI8FKA0mo:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/73403654b056998f4e8f6ac977c2912776f5588d/backend/api/tests/views/test_user.py#L112)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

remove "check" pretext from each UT.
</blockquote></details>

Done.
___
*[`backend/api/tests/views/test_user.py` line 123 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-NpeFS7HB_qrugWvGfo7:-NpeyTff8p5FlJfpbjv8:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/73403654b056998f4e8f6ac977c2912776f5588d/backend/api/tests/views/test_user.py#L123)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

for each of the test_reset_password UTs, don't use self._request_reset_password_response to setup the test.

we shouldn't do more than one HTTP call per UT.

This is because this data won't be returned in the final implementation of the endpoint (when it actually sends the email).

Instead, you should:

1.  delete this helper function and override `def setUp`.
2. in setUp, get the user
3. at the top, import default_token_generator
4.  in setUp, create a token for the user
5. `.reverse("reset-password", kwargs={"pk": self.user.pk, "token": self.token})`
</blockquote></details>

Done.
___
*[`backend/api/tests/views/test_user.py` line 147 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-NpeH7gC5sQNW8LBekL8:-NpeyZyA4PW5BM5zWjK0:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/73403654b056998f4e8f6ac977c2912776f5588d/backend/api/tests/views/test_user.py#L147)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

rename to just response after you remove the first request. do this for each test case
</blockquote></details>

Done.
___
*[`backend/api/tests/views/test_user.py` line 160 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-NpeHfVO9h-BLx-f82DD:-NpezQ3k79gQVHd2fqgr:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/73403654b056998f4e8f6ac977c2912776f5588d/backend/api/tests/views/test_user.py#L160)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

remove the get from here and create dedciated test for it.

we shouldn't do more than one HTTP call per UT.
</blockquote></details>

Done.
___
*[`backend/api/tests/views/test_user.py` line 162 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-NpeIhy24fGevAVcns-E:-NpeybMHDzM0M6sUYIih:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/73403654b056998f4e8f6ac977c2912776f5588d/backend/api/tests/views/test_user.py#L162)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

remove comment. repeating docstring
</blockquote></details>

Done.
___
*[`backend/api/tests/views/test_user.py` line 164 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-NpeIKku20PUKRLKAfAi:-NpeyjMFAeG3Dyl6PFPE:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/73403654b056998f4e8f6ac977c2912776f5588d/backend/api/tests/views/test_user.py#L164)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

`user = self.client.login(...)`

you then need to assert that user is not None
</blockquote></details>

Done.
___
*[`backend/api/tests/views/test_user.py` line 165 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-NpeIHq_69S3xTFbZYvn:-Npeyjea0X3wCFw8xcMH:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/73403654b056998f4e8f6ac977c2912776f5588d/backend/api/tests/views/test_user.py#L165)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

no need to logout.
</blockquote></details>

Done.
___
*[`backend/api/tests/views/test_user.py` line 172 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258#-NpeHplx7NvGLxVs6Oc1:-NpeymYHC6o0MuLCG1GM:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/73403654b056998f4e8f6ac977c2912776f5588d/backend/api/tests/views/test_user.py#L172)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

remove the get from here and create dedciated test for it.

we should [...]

2024-02-02 18:18 UTC, SKairinos approved these changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/258)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @faucomte97)



<!-- Sent from Reviewable.io -->

2024-02-02 18:19 UTC, merged