Invite teacher
ocadotechnology/codeforlife-portal-react pull request #264
Opened 2024-02-09 11:04 UTC by faucomte97

2024-02-12 17:03 UTC, SKairinos requested changes
> Reviewed 8 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264)* status: 8 of 15 files reviewed, 14 unresolved discussions (waiting on @faucomte97)

___
*[`.github/workflows/main.yml` line 4 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqSh-Uh0SXmeU7kzG7r:-NqSh-Uh0SXmeU7kzG7s:bb7r2f0) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/11d23bf82bb6cda4d0272db734f0d5a806a184d4/.github/workflows/main.yml#L4)):*
> ```YAML
> 
> on:
>   pull_request:
> ```

why?
___
*[`backend/api/fixtures/school_1.json` line 122 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqShKvF-LutWkaH0p_c:-NqShKvF-LutWkaH0p_d:b-ezh9bo) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/11d23bf82bb6cda4d0272db734f0d5a806a184d4/backend/api/fixtures/school_1.json#L122)):*
> ```JSON
>       "invited_teacher_last_name": "Teacher",
>       "invited_teacher_email": "invited@teacher.com",
>       "invited_teacher_is_admin": "False",
> ```

why isn't this a boolean?
___
*[`backend/api/fixtures/school_1.json` line 123 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqShayY8t7I3phEUaaa:-NqShayY8t7I3phEUaab:b-1jl8ra) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/11d23bf82bb6cda4d0272db734f0d5a806a184d4/backend/api/fixtures/school_1.json#L123)):*
> ```JSON
>       "invited_teacher_email": "invited@teacher.com",
>       "invited_teacher_is_admin": "False",
>       "expiry": "2024-02-09 20:26:08.298402"
> ```

Missing TZ info "2024-02-09 10:26:08.0+00:00"
___
*[`backend/api/serializers/school_teacher_invitation.py` line 27 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqShzNQ02DIPDYUsoEl:-NqShzNQ02DIPDYUsoEm:bm0zdwt) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/11d23bf82bb6cda4d0272db734f0d5a806a184d4/backend/api/serializers/school_teacher_invitation.py#L27)):*
> ```Python
>             "invited_teacher_first_name",
>             "invited_teacher_last_name",
>             "invited_teacher_email",
> ```

add a validation that this email is not already taken
___
*[`backend/api/serializers/school_teacher_invitation.py` line 29 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqSi47YEAHWgGLDGe2n:-NqSi47YEAHWgGLDGe2o:bfr80q5) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/11d23bf82bb6cda4d0272db734f0d5a806a184d4/backend/api/serializers/school_teacher_invitation.py#L29)):*
> ```Python
>             "invited_teacher_email",
>             "invited_teacher_is_admin",
>             "expiry",
> ```

should be set as read_only in extra_kwargs
___
*[`backend/api/serializers/school_teacher_invitation.py` line 33 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqSi8ix7gUE-gjH769_:-NqSi8ix7gUE-gjH769a:bio82wp) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/11d23bf82bb6cda4d0272db734f0d5a806a184d4/backend/api/serializers/school_teacher_invitation.py#L33)):*
> ```Python
> 
>     def create(self, validated_data):
>         token = uuid4().hex
> ```

remove this line and place it directly in the dict below
___
*[`backend/api/serializers/school_teacher_invitation.py` line 41 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqSiQ3G3T0kJUEH2VlV:-NqSiQ3G3T0kJUEH2VlW:b6ojtb6) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/11d23bf82bb6cda4d0272db734f0d5a806a184d4/backend/api/serializers/school_teacher_invitation.py#L41)):*
> ```Python
>                 "school": user.teacher.school,
>                 "from_teacher": user.teacher,
>                 "invited_teacher_first_name": validated_data["first_name"],
> ```

repeat the steps for the following fields: first_name, last_name, email, is_admin

1. in this serializer, create a field of the appropriate type
2. set the source to be the name of the field on the model.

For example: `first_name = serializers.CharField(source="invited_teacher_first_name")`

NOTE: `validated_data` will contain the keys used in `source`. Therefore, you do not need to do the mappings.
"invited_teacher_first_name" in validated_data (True)
"first_name" in validated_data (False)
Therefore, instead of creating a mapping, do this:

```validated_data["token"] = uuid4().hex
validated_data["school"] = user.teacher.school
validated_data["from_teacher"] = user.teacher
validated_data["expiry"] = timezone.now() + timedelta(days=30)
return super().create(validated_data)```
```

___
*[`backend/api/signals/school_teacher_invitation.py` line 16 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqSkIFc4vyCT7duQ2XD:-NqSkIFc4vyCT7duQ2XE:b-zais5c) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/11d23bf82bb6cda4d0272db734f0d5a806a184d4/backend/api/signals/school_teacher_invitation.py#L16)):*
> ```Python
> # pylint: disable=unused-argument
> @receiver(post_save, sender=SchoolTeacherInvitation)
> def user__post_save(sender, instance: SchoolTeacherInvitation, *args, **kwargs):
> ```

school_teacher_invitation__post_save
___
*[`backend/api/signals/school_teacher_invitation.py` line 17 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqSkSEu0EW73krxJ1i6:-NqSkSEu0EW73krxJ1i7:b-1k6ex5) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/11d23bf82bb6cda4d0272db734f0d5a806a184d4/backend/api/signals/school_teacher_invitation.py#L17)):*
> ```Python
> @receiver(post_save, sender=SchoolTeacherInvitation)
> def user__post_save(sender, instance: SchoolTeacherInvitation, *args, **kwargs):
>     """After a SchoolTeacherInvitation is created."""
> ```

There's no need to document what's triggering the signal.
Your docstring should say what your comment is saying.
Docstring should describe what's happening in this signal.

something like: "Send email to invited teacher..."
___
*[`backend/api/views/user.py` line 137 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqSl5Dj3F1-GdX0MZ7S:-NqSl5Dj3F1-GdX0MZ7T:bfw9enh) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/11d23bf82bb6cda4d0272db734f0d5a806a184d4/backend/api/views/user.py#L137)):*
> ```Python
>         permission_classes=[AllowAny],
>     )
>     def accept_invite(self, request: Request, token: t.Optional[str] = None):
> ```

this action needs to move to the SchoolTeacherInvitationViewSet.

set detail = True so we can the specific pk of the invite.
___
*[`backend/api/views/user.py` line 144 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqSlLp_EdJmRufXoVVe:-NqSlLp_EdJmRufXoVVf:bq1135z) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/11d23bf82bb6cda4d0272db734f0d5a806a184d4/backend/api/views/user.py#L144)):*
> ```Python
>         """
>         try:
>             invitation = SchoolTeacherInvitation.objects.get(token=token)
> ```

.get(pk=pk)
___
*[`backend/api/views/user.py` line 146 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqSlT-r7EhxaH3WGHWF:-NqSlT-r7EhxaH3WGHWG:b7kobt5) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/11d23bf82bb6cda4d0272db734f0d5a806a184d4/backend/api/views/user.py#L146)):*
> ```Python
>             invitation = SchoolTeacherInvitation.objects.get(token=token)
> 
>             if invitation.is_expired:
> ```

should be outside the try block
___
*[`backend/api/views/user.py` line 146 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqSld6a-1KasQ5j1VEo:-NqSld6a-1KasQ5j1VEp:b-q0ddzw) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/11d23bf82bb6cda4d0272db734f0d5a806a [...]

2024-02-13 14:59 UTC, faucomte97 reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264)* status: 6 of 16 files reviewed, 14 unresolved discussions (waiting on @faucomte97 and @SKairinos)

___
*[`.github/workflows/main.yml` line 4 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqSh-Uh0SXmeU7kzG7r:-NqXxF5G9kDXTC7odUbu:b-d3g3yq) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/11d23bf82bb6cda4d0272db734f0d5a806a184d4/.github/workflows/main.yml#L4)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

why?
</blockquote></details>

Cuz I wan code quality check on evri PR commit init
___
*[`backend/api/fixtures/school_1.json` line 122 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqShKvF-LutWkaH0p_c:-NqXxONR1Iy0mtos1a9D:b4jobxb) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/11d23bf82bb6cda4d0272db734f0d5a806a184d4/backend/api/fixtures/school_1.json#L122)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

why isn't this a boolean?
</blockquote></details>

¯\_(ツ)_/¯
___
*[`backend/api/fixtures/school_1.json` line 123 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqShayY8t7I3phEUaaa:-NqXxb5W0hgnf0vGA_Ow:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/11d23bf82bb6cda4d0272db734f0d5a806a184d4/backend/api/fixtures/school_1.json#L123)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

Missing TZ info "2024-02-09 10:26:08.0+00:00"
</blockquote></details>

Done.
___
*[`backend/api/serializers/school_teacher_invitation.py` line 27 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqShzNQ02DIPDYUsoEl:-NqXyaHq0Wkyr83A4Afl:b-g4sd4c) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/11d23bf82bb6cda4d0272db734f0d5a806a184d4/backend/api/serializers/school_teacher_invitation.py#L27)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

add a validation that this email is not already taken
</blockquote></details>

no cos enumeration
___
*[`backend/api/serializers/school_teacher_invitation.py` line 29 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqSi47YEAHWgGLDGe2n:-NqXxdqDCf5RSTf_DyOr:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/11d23bf82bb6cda4d0272db734f0d5a806a184d4/backend/api/serializers/school_teacher_invitation.py#L29)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

should be set as read_only in extra_kwargs
</blockquote></details>

Done.
___
*[`backend/api/serializers/school_teacher_invitation.py` line 33 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqSi8ix7gUE-gjH769_:-NqXxngF-7lyAxCTG2Eu:b-a64uiz) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/11d23bf82bb6cda4d0272db734f0d5a806a184d4/backend/api/serializers/school_teacher_invitation.py#L33)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

remove this line and place it directly in the dict below
</blockquote></details>

No longer relevant I think
___
*[`backend/api/serializers/school_teacher_invitation.py` line 41 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqSiQ3G3T0kJUEH2VlV:-NqXxrLc6Qkx5YfBRQQY:b-4vnb5) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/11d23bf82bb6cda4d0272db734f0d5a806a184d4/backend/api/serializers/school_teacher_invitation.py#L41)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

repeat the steps for the following fields: first_name, last_name, email, is_admin

1. in this serializer, create a field of the appropriate type
2. set the source to be the name of the field on the model.

For example: `first_name = serializers.CharField(source="invited_teacher_first_name")`

NOTE: `validated_data` will contain the keys used in `source`. Therefore, you do not need to do the mappings.
"invited_teacher_first_name" in validated_data (True)
"first_name" in validated_data (False)
Therefore, instead of creating a mapping, do this:

```validated_data["token"] = uuid4().hex
validated_data["school"] = user.teacher.school
validated_data["from_teacher"] = user.teacher
validated_data["expiry"] = timezone.now() + timedelta(days=30)
return super().create(validated_data)```
```

</blockquote></details>

Done / no longer relevant
___
*[`backend/api/signals/school_teacher_invitation.py` line 16 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqSkIFc4vyCT7duQ2XD:-NqXy2qq-k8_ASdnfGNm:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/11d23bf82bb6cda4d0272db734f0d5a806a184d4/backend/api/signals/school_teacher_invitation.py#L16)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

school_teacher_invitation__post_save
</blockquote></details>

Done.
___
*[`backend/api/signals/school_teacher_invitation.py` line 17 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqSkSEu0EW73krxJ1i6:-NqXyN-V9Iqx3GOjD387:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/11d23bf82bb6cda4d0272db734f0d5a806a184d4/backend/api/signals/school_teacher_invitation.py#L17)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

There's no need to document what's triggering the signal.
Your docstring should say what your comment is saying.
Docstring should describe what's happening in this signal.

something like: "Send email to invited teacher..."
</blockquote></details>

Done.
___
*[`backend/api/views/user.py` line 137 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqSl5Dj3F1-GdX0MZ7S:-NqXyVVZ9bZiuRA35wv4:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/11d23bf82bb6cda4d0272db734f0d5a806a184d4/backend/api/views/user.py#L137)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

this action needs to move to the SchoolTeacherInvitationViewSet.

set detail = True so we can the specific pk of the invite.
</blockquote></details>

Done.
___
*[`backend/api/views/user.py` line 144 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqSlLp_EdJmRufXoVVe:-NqXyVmuBNeklDb_Htgu:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/11d23bf82bb6cda4d0272db734f0d5a806a184d4/backend/api/views/user.py#L144)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

.get(pk=pk)
</blockquote></details>

Done.
___
*[`backend/api/views/user.py` line 146 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqSlT-r7EhxaH3WGHWF:-NqXyWBL37krdU7Jykcq:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/11d23bf82bb6cda4d0272db734f0d5a806a184d4/backend/api/views/user.py#L146)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

should be outside the try block
</blockquote></details>

Done.
___
*[`backend/api/views/user.py` line 146 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqSld6a-1KasQ5j1VEo:-NqXyXASEEsri2wfSv5l:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/11d23bf82bb6cda4d0272db734f0d5a806a184d4/backend/api/views/user.py#L146)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

should you delete the invi [...]

2024-02-13 15:31 UTC, SKairinos requested changes
> Reviewed 1 of 15 files at r1, 1 of 6 files at r2, 4 of 7 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264)* status: all files reviewed, 23 unresolved discussions (waiting on @faucomte97)

___
*[`backend/api/serializers/user.py` line 140 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqY-FM4DuP7Xs54HDYR:-NqY-FM4DuP7Xs54HDYS:b-qzscaf) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/312ea28eacc3df794b662e541157dc6e6256f56b/backend/api/serializers/user.py#L140)):*
> ```Python
>             "reset-password",
>             "invite-teacher",
>             "accept-invite",
> ```

```
if self.instance is not None and self.view.action != "reset-password":
    pass # TODO: current_password is required
```
___
*[`backend/api/serializers/user.py` line 145 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqY0-4bDWaabUX7MkvG:-NqY0-4bDWaabUX7MkvH:br2mdcy) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/312ea28eacc3df794b662e541157dc6e6256f56b/backend/api/serializers/user.py#L145)):*
> ```Python
>             # TODO: make current password required when changing self-profile.
> 
>         # TODO: validate last_name is required if teacher-user.
> ```

```
if "new_teacher" in attrs and "last_name" not in attrs:
    raise serializers.ValidationError()
```
___
*[`backend/api/serializers/user.py` line 177 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqY0Lbo9nyFAcrJvqie:-NqY0Lbo9nyFAcrJvqif:bbipsc9) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/312ea28eacc3df794b662e541157dc6e6256f56b/backend/api/serializers/user.py#L177)):*
> ```Python
>             password=validated_data["password"],
>             first_name=validated_data["first_name"],
>             last_name=validated_data["last_name"],
> ```

validated_data.get("last_name")
___
*[`backend/api/tests/serializers/test_school_teacher_invitation.py` line 31 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqY1e0O6R12HH2HUOPT:-NqY1e0O6R12HH2HUOPU:b-jq6rv5) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/312ea28eacc3df794b662e541157dc6e6256f56b/backend/api/tests/serializers/test_school_teacher_invitation.py#L31)):*
> ```Python
>         """
> 
>         self.assert_create(
> ```

assert new_data

```
new_data = {
 "token": "...",
"school": "...",
"from_teacher": "...",
"expiry": "...",
}
```

for token, you will need to mock make_password.
for expiry, you will need to mock timezone.now().
___
*[`backend/api/tests/serializers/test_school_teacher_invitation.py` line 50 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqY27sRDTs0rl5eGpXc:-NqY27sRDTs0rl5eGpXd:b-r5rn7) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/312ea28eacc3df794b662e541157dc6e6256f56b/backend/api/tests/serializers/test_school_teacher_invitation.py#L50)):*
> ```Python
>         """
> 
>         self.assert_update(
> ```

assert new_data

```
new_data = {
"expiry": "...",
}
```

for expiry, you will need to mock timezone.now().
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 33 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqY2HMX8SELVyO2P1RY:-NqY2HMX8SELVyO2P1RZ:b36h12a) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/312ea28eacc3df794b662e541157dc6e6256f56b/backend/api/tests/views/test_school_teacher_invitation.py#L33)):*
> ```Python
>     def _login_admin_school_teacher(self):
>         return self.client.login_school_teacher(
>             email="admin.teacher@school1.com",
> ```

use class variable
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 46 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqY2PO5EhXcFOE2J6Jw:-NqY2PO5EhXcFOE2J6Jx:bh8w1pg) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/312ea28eacc3df794b662e541157dc6e6256f56b/backend/api/tests/views/test_school_teacher_invitation.py#L46)):*
> ```Python
>         is_admin: bool,
>     ):
>         host_teacher = Teacher.objects.get(
> ```

AdminSchoolTeacher
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 94 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqY2ePa9bpMhx7KSzAt:-NqY2ePa9bpMhx7KSzAu:b-c3160w) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/312ea28eacc3df794b662e541157dc6e6256f56b/backend/api/tests/views/test_school_teacher_invitation.py#L94)):*
> ```Python
>         )
> 
>     def test_get_permissions__retrieve(self):
> ```

forgot list action
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 129 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqY2pgk07mqyok29WYf:-NqY2pgk07mqyok29WYg:b-3dbd41) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/312ea28eacc3df794b662e541157dc6e6256f56b/backend/api/tests/views/test_school_teacher_invitation.py#L129)):*
> ```Python
>         self._login_admin_school_teacher()
> 
>         invitation = SchoolTeacherInvitation.objects.get(pk=1)
> ```

use self.invitation instead
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 144 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqY36hH3bRITdxCcpah:-NqY36hH3bRITdxCcpai:b-3dbd41) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/312ea28eacc3df794b662e541157dc6e6256f56b/backend/api/tests/views/test_school_teacher_invitation.py#L144)):*
> ```Python
>         self._login_admin_school_teacher()
> 
>         invitation = SchoolTeacherInvitation.objects.get(pk=1)
> ```

use self.invitation instead
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 148 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqY38Nc-zu-Ha0WXpFz:-NqY38Nc-zu-Ha0WXpG-:bxpqvon) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/312ea28eacc3df794b662e541157dc6e6256f56b/backend/api/tests/views/test_school_teacher_invitation.py#L148)):*
> ```Python
>         self.client.destroy(invitation)
> 
>         assert not SchoolTeacherInvitation.objects.filter(pk=1).exists()
> ```

assert raises does not exist
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 150 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqY3g4DBrOUWEFuAsHh:-NqY3g4DBrOUWEFuAsHi:b-f4jvat) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/312ea28eacc3df794b662e541157dc6e6256f56b/backend/api/tests/views/test_school_teacher_invitation.py#L150)):*
> ```Python
>         assert not SchoolTeacherInvitation.objects.filter(pk=1).exists()
> 
>     def test_accept__invalid_token(self):
> ```

test_accept__get__invalid_token
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 153 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqY3NXeBAdEZcSRMCav:-NqY3NXeBAdEZcSRMCaw:b-el6w8l) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/312ea28eacc3df794b662e541157dc6e6256f56b/backend/api/tests/views/test_school_teacher_invitation.py#L153)):*
> ```Python
>         """Accept invite raises 400 on GET with invalid token"""
> 
>         invitation = self._invite_teacher(
> ```

use fixture
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 173 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqY3lh7Dlzb53uFXt35:-NqY3lh7Dlzb53uFXt36:b-d2bg3l) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/312ea28eacc3df794b662e541157dc6e6256f56b/backend/api/tests/views/test [...]

2024-02-13 15:32 UTC, SKairinos requested changes
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264)* status: all files reviewed, 23 unresolved discussions (waiting on @faucomte97)

___
*[`.github/workflows/main.yml` line 4 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqSh-Uh0SXmeU7kzG7r:-NqY5JQj6eYay-ic_uDl:b-4rhsp1) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/11d23bf82bb6cda4d0272db734f0d5a806a184d4/.github/workflows/main.yml#L4)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Cuz I wan code quality check on evri PR commit init
</blockquote></details>

try removing it and test again


<!-- Sent from Reviewable.io -->

2024-02-13 17:44 UTC, faucomte97 reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264)* status: 8 of 18 files reviewed, 22 unresolved discussions (waiting on @faucomte97 and @SKairinos)

___
*[`backend/api/serializers/user.py` line 140 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqY-FM4DuP7Xs54HDYR:-NqY6yYV48fBjVrCxgW6:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/312ea28eacc3df794b662e541157dc6e6256f56b/backend/api/serializers/user.py#L140)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

```
if self.instance is not None and self.view.action != "reset-password":
    pass # TODO: current_password is required
```
</blockquote></details>

Done.
___
*[`backend/api/serializers/user.py` line 145 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqY0-4bDWaabUX7MkvG:-NqY7I5k3GRVCT9mh0Bs:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/312ea28eacc3df794b662e541157dc6e6256f56b/backend/api/serializers/user.py#L145)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

```
if "new_teacher" in attrs and "last_name" not in attrs:
    raise serializers.ValidationError()
```
</blockquote></details>

Done.
___
*[`backend/api/serializers/user.py` line 177 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqY0Lbo9nyFAcrJvqie:-NqY7kd3D1eXtBCengT2:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/312ea28eacc3df794b662e541157dc6e6256f56b/backend/api/serializers/user.py#L177)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

validated_data.get("last_name")
</blockquote></details>

Done.
___
*[`backend/api/tests/serializers/test_school_teacher_invitation.py` line 31 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqY1e0O6R12HH2HUOPT:-NqYXn3fEWmFcAOqerfq:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/312ea28eacc3df794b662e541157dc6e6256f56b/backend/api/tests/serializers/test_school_teacher_invitation.py#L31)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

assert new_data

```
new_data = {
 "token": "...",
"school": "...",
"from_teacher": "...",
"expiry": "...",
}
```

for token, you will need to mock make_password.
for expiry, you will need to mock timezone.now().
</blockquote></details>

Done.
___
*[`backend/api/tests/serializers/test_school_teacher_invitation.py` line 50 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqY27sRDTs0rl5eGpXc:-NqYZNXt-9qy2qllfD1I:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/312ea28eacc3df794b662e541157dc6e6256f56b/backend/api/tests/serializers/test_school_teacher_invitation.py#L50)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

assert new_data

```
new_data = {
"expiry": "...",
}
```

for expiry, you will need to mock timezone.now().
</blockquote></details>

Done.
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 33 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqY2HMX8SELVyO2P1RY:-NqY86uO2YBIO4DgpZCW:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/312ea28eacc3df794b662e541157dc6e6256f56b/backend/api/tests/views/test_school_teacher_invitation.py#L33)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

use class variable
</blockquote></details>

Done.
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 46 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqY2PO5EhXcFOE2J6Jw:-NqY8BWlDppJr9zyQRDB:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/312ea28eacc3df794b662e541157dc6e6256f56b/backend/api/tests/views/test_school_teacher_invitation.py#L46)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

AdminSchoolTeacher
</blockquote></details>

Done.
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 94 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqY2ePa9bpMhx7KSzAt:-NqY8H8W5AmHKzwkZibD:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/312ea28eacc3df794b662e541157dc6e6256f56b/backend/api/tests/views/test_school_teacher_invitation.py#L94)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

forgot list action
</blockquote></details>

Done.
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 129 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqY2pgk07mqyok29WYf:-NqY8MaG9RX-BCNHfmp8:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/312ea28eacc3df794b662e541157dc6e6256f56b/backend/api/tests/views/test_school_teacher_invitation.py#L129)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

use self.invitation instead
</blockquote></details>

Done.
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 144 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqY36hH3bRITdxCcpah:-NqY8N1L5RqLmQ6vLMw_:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/312ea28eacc3df794b662e541157dc6e6256f56b/backend/api/tests/views/test_school_teacher_invitation.py#L144)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

use self.invitation instead
</blockquote></details>

Done.
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 148 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqY38Nc-zu-Ha0WXpFz:-NqY8dtl7MGAUwFoPQU6:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/312ea28eacc3df794b662e541157dc6e6256f56b/backend/api/tests/views/test_school_teacher_invitation.py#L148)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

assert raises does not exist
</blockquote></details>

Done.
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 150 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqY3g4DBrOUWEFuAsHh:-NqY8d_H1_t_FYpBX0ps:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/312ea28eacc3df794b662e541157dc6e6256f56b/backend/api/tests/views/test_school_teacher_invitation.py#L150)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

test_accept__get__invalid_token
</blockquote></details>

Done.
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 153 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqY3NXeBAdEZcSRMCav:-NqY9vFYEkNfa55iOFuf:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/312ea28eacc3df794b662e541157dc6e6256f56b/backend/api/tests/views/test_school_teacher_invitation.py#L153)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

use fixture
</blockquote></details>

Done.
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 173 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqY3lh7Dlzb53uFXt35:-NqY9wPNB1KJ6CxonCdd:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/312ea28eacc3df794b662e541157dc6e6256f56b/backend/api/tests/views/test_school_teacher_invitation.py#L173)):*
<details><summary><i>Previou [...]

2024-02-14 10:36 UTC, SKairinos requested changes
> Reviewed 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264)* status: all files reviewed, 11 unresolved discussions (waiting on @faucomte97)

___
*[`backend/api/fixtures/school_1.json` line 130 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqaxBYN91_kGBUw_6OD:-NqaxBYN91_kGBUw_6OE:b-z7vijh) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/ece6fb5464682e425d3d3293cdaeaad652060b47/backend/api/fixtures/school_1.json#L130)):*
> ```JSON
>     "pk": 2,
>     "fields": {
>       "token": "whatever",
> ```

needs to have the hash. copy from above. this is not a valid fixture because the token will never look like this in the db.  
___
*[`backend/api/fixtures/school_1.json` line 141 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-Nqaxq_A4q6PDhvGOYkh:-Nqaxq_A4q6PDhvGOYki:b-z9sw3w) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/ece6fb5464682e425d3d3293cdaeaad652060b47/backend/api/fixtures/school_1.json#L141)):*
> ```JSON
>   },
>   {
>     "model": "common.schoolteacherinvitation",
> ```

duplicate. what's the point of this?

as I see it, you need 3 invitation fixtures:
(pk=1) an expired invitation
(pk=2) a non-expired invitation for a teacher not already in a school.
(pk=3) a non-expired invitation for a teacher already in a school.

ALL 3 should have the token field set with the valid hash. This should always be the case.
___
*[`backend/api/tests/serializers/test_school_teacher_invitation.py` line 67 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-Nqb261g-cXwIyniNtle:-Nqb261g-cXwIyniNtlf:b75rpab) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/ece6fb5464682e425d3d3293cdaeaad652060b47/backend/api/tests/serializers/test_school_teacher_invitation.py#L67)):*
> ```Python
>                     "expiry": now + datetime.timedelta(days=30),
>                 },
>                 context={
> ```

context is not need in this test. notice we don't utilize the context in our overridden update() function on the serializer
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 38 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-Nqb-3TU8e6okN3PTWE_:-Nqb-3TU8e6okN3PTWEa:bh0d6p4) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/312ea28eacc3df794b662e541157dc6e6256f56b/backend/api/tests/views/test_school_teacher_invitation.py#L38)):*
> ```Python
>         )
> 
>     def _invite_teacher(
> ```

remove helper function. use fixtures
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 68 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-Nqb46zBA0e0tb9mkKPE:-Nqb46zBA0e0tb9mkKPF:b-cds66t) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/ece6fb5464682e425d3d3293cdaeaad652060b47/backend/api/tests/views/test_school_teacher_invitation.py#L68)):*
> ```Python
> 
>     def setUp(self):
>         self.expired_invitation = SchoolTeacherInvitation.objects.get(pk=1)
> ```

assert that the invitation has expired
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 69 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-Nqb-Ehd1hRkJ38IeYEM:-Nqb-Ehd1hRkJ38IeYEN:b8yh0pz) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/ece6fb5464682e425d3d3293cdaeaad652060b47/backend/api/tests/views/test_school_teacher_invitation.py#L69)):*
> ```Python
>     def setUp(self):
>         self.expired_invitation = SchoolTeacherInvitation.objects.get(pk=1)
>         self.invalid_token_invitation = SchoolTeacherInvitation.objects.get(
> ```

unnecessary

the token will always be "valid" on the db (i.e. it should have the hashed version of "token"). HOWEVER, when you're calling the /accept, you'll pass in the incorrect raw token (something other than "token").
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 72 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-Nqb-cK9Etp0_ri5NRoH:-Nqb-cKA3A10Po3iby-o:b-av0oj3) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/ece6fb5464682e425d3d3293cdaeaad652060b47/backend/api/tests/views/test_school_teacher_invitation.py#L72)):*
> ```Python
>             pk=2
>         )
>         self.valid_invitation = SchoolTeacherInvitation.objects.get(pk=3)
> ```

rename to new_teacher_invitation.
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 72 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-Nqb4Fm4BoHvtbk-XmYK:-Nqb4Fm4BoHvtbk-XmYL:b-c7bwt4) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/ece6fb5464682e425d3d3293cdaeaad652060b47/backend/api/tests/views/test_school_teacher_invitation.py#L72)):*
> ```Python
>             pk=2
>         )
>         self.valid_invitation = SchoolTeacherInvitation.objects.get(pk=3)
> ```

assert that the invitation has not expired and the invited teacher is not in a school
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 73 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-Nqb4L6F4aSlK4Sl9vLR:-Nqb4L6F4aSlK4Sl9vLS:b-dm64y3) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/ece6fb5464682e425d3d3293cdaeaad652060b47/backend/api/tests/views/test_school_teacher_invitation.py#L73)):*
> ```Python
>         )
>         self.valid_invitation = SchoolTeacherInvitation.objects.get(pk=3)
>         self.existing_teacher_invitation = SchoolTeacherInvitation.objects.get(
> ```

assert that the invitation has not expired and the invited teacher is in a school
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 157 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-Nqb9BrYBnnYDYO2UFL5:-Nqb9BrYBnnYDYO2UFL6:b-wsg12o) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/ece6fb5464682e425d3d3293cdaeaad652060b47/backend/api/tests/views/test_school_teacher_invitation.py#L157)):*
> ```Python
>     def test_accept__get__invalid_token(self):
>         """Accept invite raises 400 on GET with invalid token"""
>         invitation = self.invalid_token_invitation
> ```

use a "vaild"/non-expired invitation. instead, set the "token" kwarg to anything other than "token"

"token": "whatever"
___
*[`backend/api/tests/views/test_user.py` line 32 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqbAjZy6SzSk8QOcDB3:-NqbAjZy6SzSk8QOcDB4:bpp6stj) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/d6b953cd4756b2a5679a10bb0f447bb80b0c3a91/backend/api/tests/views/test_user.py#L32)):*
> ```Python
>     school_teacher_email = "teacher@school1.com"
>     school_admin_teacher_email = "admin.teacher@school1.com"
>     school_name = "School 1"
> ```

not needed


<!-- Sent from Reviewable.io -->

2024-02-14 10:39 UTC, SKairinos requested changes
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264)* status: all files reviewed, 12 unresolved discussions (waiting on @faucomte97)

___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 10 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqbBj1N2ucOMj1NQvg1:-NqbBj1N2ucOMj1NQvg2:b-sidx1z) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/ece6fb5464682e425d3d3293cdaeaad652060b47/backend/api/tests/views/test_school_teacher_invitation.py#L10)):*
> ```Python
> from codeforlife.permissions import AllowNone
> from codeforlife.tests import ModelViewSetTestCase
> from codeforlife.user.models import AdminSchoolTeacher, School, Teacher
> ```

unused imports


<!-- Sent from Reviewable.io -->

2024-02-14 10:57 UTC, faucomte97 reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264)* status: all files reviewed, 12 unresolved discussions (waiting on @SKairinos)

___
*[`backend/api/fixtures/school_1.json` line 130 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqaxBYN91_kGBUw_6OD:-NqbC4Wi5tpd4a2t3pnS:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/ece6fb5464682e425d3d3293cdaeaad652060b47/backend/api/fixtures/school_1.json#L130)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

needs to have the hash. copy from above. this is not a valid fixture because the token will never look like this in the db.
</blockquote></details>

Done.
___
*[`backend/api/fixtures/school_1.json` line 141 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-Nqaxq_A4q6PDhvGOYkh:-NqbC6raALj0p4L00eve:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/ece6fb5464682e425d3d3293cdaeaad652060b47/backend/api/fixtures/school_1.json#L141)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

duplicate. what's the point of this?

as I see it, you need 3 invitation fixtures:
(pk=1) an expired invitation
(pk=2) a non-expired invitation for a teacher not already in a school.
(pk=3) a non-expired invitation for a teacher already in a school.

ALL 3 should have the token field set with the valid hash. This should always be the case.
</blockquote></details>

Done.
___
*[`backend/api/tests/serializers/test_school_teacher_invitation.py` line 67 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-Nqb261g-cXwIyniNtle:-NqbCMY6-bP9SlZPmq2u:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/ece6fb5464682e425d3d3293cdaeaad652060b47/backend/api/tests/serializers/test_school_teacher_invitation.py#L67)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

context is not need in this test. notice we don't utilize the context in our overridden update() function on the serializer
</blockquote></details>

Done.
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 38 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-Nqb-3TU8e6okN3PTWE_:-NqbCY-6-U52d_uCESn6:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/312ea28eacc3df794b662e541157dc6e6256f56b/backend/api/tests/views/test_school_teacher_invitation.py#L38)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

remove helper function. use fixtures
</blockquote></details>

Done.
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 10 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqbBj1N2ucOMj1NQvg1:-NqbCRbZ6JmjWz0nAqG_:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/ece6fb5464682e425d3d3293cdaeaad652060b47/backend/api/tests/views/test_school_teacher_invitation.py#L10)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

unused imports
</blockquote></details>

Done.
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 68 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-Nqb46zBA0e0tb9mkKPE:-NqbCyxu1cWmya9DdVt4:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/ece6fb5464682e425d3d3293cdaeaad652060b47/backend/api/tests/views/test_school_teacher_invitation.py#L68)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

assert that the invitation has expired
</blockquote></details>

Done.
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 69 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-Nqb-Ehd1hRkJ38IeYEM:-NqbCzlu0HWmVrnbRB4Z:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/ece6fb5464682e425d3d3293cdaeaad652060b47/backend/api/tests/views/test_school_teacher_invitation.py#L69)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

unnecessary

the token will always be "valid" on the db (i.e. it should have the hashed version of "token"). HOWEVER, when you're calling the /accept, you'll pass in the incorrect raw token (something other than "token").
</blockquote></details>

Done.
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 72 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-Nqb-cK9Etp0_ri5NRoH:-NqbDwSa8G0sbpdFsF7N:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/ece6fb5464682e425d3d3293cdaeaad652060b47/backend/api/tests/views/test_school_teacher_invitation.py#L72)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

rename to new_teacher_invitation.
</blockquote></details>

Done.
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 72 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-Nqb4Fm4BoHvtbk-XmYK:-NqbELtv0p7t-vqiy17q:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/ece6fb5464682e425d3d3293cdaeaad652060b47/backend/api/tests/views/test_school_teacher_invitation.py#L72)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

assert that the invitation has not expired and the invited teacher is not in a school
</blockquote></details>

Done.
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 73 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-Nqb4L6F4aSlK4Sl9vLR:-NqbEr9T3ZidAt8tTf9g:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/ece6fb5464682e425d3d3293cdaeaad652060b47/backend/api/tests/views/test_school_teacher_invitation.py#L73)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

assert that the invitation has not expired and the invited teacher is in a school
</blockquote></details>

Done.
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 157 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-Nqb9BrYBnnYDYO2UFL5:-NqbFbh_9DeDpHKGTgRI:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/ece6fb5464682e425d3d3293cdaeaad652060b47/backend/api/tests/views/test_school_teacher_invitation.py#L157)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

use a "vaild"/non-expired invitation. instead, set the "token" kwarg to anything other than "token"

"token": "whatever"
</blockquote></details>

Done.
___
*[`backend/api/tests/views/test_user.py` line 32 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqbAjZy6SzSk8QOcDB3:-NqbFiiv7eVmn7h4ie1P:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/d6b953cd4756b2a5679a10bb0f447bb80b0c3a91/backend/api/tests/views/test_user.py#L32)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

not needed
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-14 11:05 UTC, SKairinos requested changes
> Reviewed 4 of 4 files at r7, 1 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264)* status: 17 of 18 files reviewed, 3 unresolved discussions (waiting on @faucomte97)

___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 37 at r7](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqbHH95COfGTUXb0mfn:-NqbHH95COfGTUXb0mfo:b-a8ngk0) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e42d94b8784a8b55bce85751a91958e82237bf43/backend/api/tests/views/test_school_teacher_invitation.py#L37)):*
> ```Python
>         assert self.expired_invitation.is_expired
> 
>         self.new_teacher_invitation = SchoolTeacherInvitation.objects.get(pk=2)
> ```

rename to new_user_invitation since we're inviting a new user
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 45 at r7](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqbGzIcAM1FDG7-3YmB:-NqbGzIdBLvo6zbiofzG:b-dew0tu) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e42d94b8784a8b55bce85751a91958e82237bf43/backend/api/tests/views/test_school_teacher_invitation.py#L45)):*
> ```Python
>             )
> 
>         self.existing_teacher_invitation = SchoolTeacherInvitation.objects.get(
> ```

rename to existing_user_invitation since we're inviting an existing user
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 52 at r7](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqbH39U4_iTDqz9Yogj:-NqbH39U4_iTDqz9Yogk:b3iu0i1) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e42d94b8784a8b55bce85751a91958e82237bf43/backend/api/tests/views/test_school_teacher_invitation.py#L52)):*
> ```Python
>             email__iexact=self.existing_teacher_invitation.invited_teacher_email
>         )
>         assert user.teacher.school is not None
> ```

no need to assert user is in school


<!-- Sent from Reviewable.io -->

2024-02-14 11:28 UTC, faucomte97 reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264)* status: 17 of 18 files reviewed, 3 unresolved discussions (waiting on @SKairinos)

___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 37 at r7](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqbHH95COfGTUXb0mfn:-NqbKaZ74kmVKBDj3KvN:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e42d94b8784a8b55bce85751a91958e82237bf43/backend/api/tests/views/test_school_teacher_invitation.py#L37)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

rename to new_user_invitation since we're inviting a new user
</blockquote></details>

Done.
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 45 at r7](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqbGzIcAM1FDG7-3YmB:-NqbKdLk4hs233HLzQQS:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e42d94b8784a8b55bce85751a91958e82237bf43/backend/api/tests/views/test_school_teacher_invitation.py#L45)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

rename to existing_user_invitation since we're inviting an existing user
</blockquote></details>

Done.
___
*[`backend/api/tests/views/test_school_teacher_invitation.py` line 52 at r7](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-NqbH39U4_iTDqz9Yogj:-NqbKdkgETXinkjb8WZW:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e42d94b8784a8b55bce85751a91958e82237bf43/backend/api/tests/views/test_school_teacher_invitation.py#L52)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

no need to assert user is in school
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-14 11:31 UTC, SKairinos reviewed
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @faucomte97)



<!-- Sent from Reviewable.io -->

2024-02-14 11:32 UTC, SKairinos approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @faucomte97)



<!-- Sent from Reviewable.io -->

2024-02-14 11:39 UTC, SKairinos requested changes
you need to install py package v0.13.4
remember to set the version in [packages] and [dev-packages]

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/264#-:-NqbOeIJAMsT5YNJfXKe:b-iuimbu)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @faucomte97)



<!-- Sent from Reviewable.io -->

2024-02-14 13:18 UTC, merged