Handle join class requests
ocadotechnology/codeforlife-portal-react pull request #308
Opened 2024-02-21 18:53 UTC by faucomte97

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308)

2024-02-23 12:40 UTC, SKairinos requested changes
> Reviewed 13 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308)* status: 13 of 16 files reviewed, 12 unresolved discussions (waiting on @faucomte97)

___
*[`backend/api/fixtures/independent_school_1_class_1_join_request.json` line 8 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrKrX2B5iM0wA-J9V1S:-NrKrX2B5iM0wA-J9V1T:b44o3xa) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/c4918c1b8ea18824ac3f424bd3c34d9ae5ce588e/backend/api/fixtures/independent_school_1_class_1_join_request.json#L8)):*
> ```JSON
>       "user": 28,
>       "new_user": 28,
>       "pending_class_request": 7
> ```

this is actually class 2 @ school 1. Please rename file accordingly.
___
*[`backend/api/serializers/klass.py` line 104 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrKsh0H48DS8izM7mte:-NrKsh0H48DS8izM7mtf:biful5a) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/c4918c1b8ea18824ac3f424bd3c34d9ae5ce588e/backend/api/serializers/klass.py#L104)):*
> ```Python
>         )
> 
>     def update(self, instance, validated_data):
> ```

the problem with this update function is we are unable to update any other fields. let's discuss on call
___
*[`backend/api/serializers/klass.py` line 105 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrKsM3UEuqa2MlNS1YA:-NrKsM3UEuqa2MlNS1YB:ba0dsqc) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/c4918c1b8ea18824ac3f424bd3c34d9ae5ce588e/backend/api/serializers/klass.py#L105)):*
> ```Python
> 
>     def update(self, instance, validated_data):
>         # TODO: Decide how to handle this field. Currently, teachers select a
> ```

comment not needed. the FE will be responsible for sending the datetime. if the user selects a number of hours, the FE will compute the final datetime (now + 3 hours) and send it the backend. 
___
*[`backend/api/views/user.py` line 53 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrKun1-2v8Su7_vPG-5:-NrKun1010heKPo-LaKT:b-sb4aed) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/c4918c1b8ea18824ac3f424bd3c34d9ae5ce588e/backend/api/views/user.py#L53)):*
> ```Python
>             if "requesting_to_join_class" in self.request.data:
>                 return [IsIndependent()]
>         if self.action == "handle_join_class_request":
> ```

delete this if. add the action name to the list above (in ["bulk", ...])
___
*[`backend/api/views/user.py` line 227 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrKvZRf1FFT6LcEco8B:-NrKvZRf1FFT6LcEco8C:b-ne08pd) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/c4918c1b8ea18824ac3f424bd3c34d9ae5ce588e/backend/api/views/user.py#L227)):*
> ```Python
>     )
>     def handle_join_class_request(
>         self, request: Request, pk: t.Optional[str] = None
> ```

pk is not optional. The url path won't match if pk is not provided. for example, it has to be

/api/users/1/handle-join-class-request
___
*[`backend/api/views/user.py` line 232 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrKw-bR6_G97LUT0Tvq:-NrKw-bR6_G97LUT0Tvr:bbabe51) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/c4918c1b8ea18824ac3f424bd3c34d9ae5ce588e/backend/api/views/user.py#L232)):*
> ```Python
>         Handles an independent user's request to join a class. First tries to
>         retrieve the independent user, then the class they're requesting to
>         join. The teacher handling the request must either be an admin the
> ```

an admin in the
___
*[`backend/api/views/user.py` line 240 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrKwDEZ87B79GVzBlmH:-NrKwDEZ87B79GVzBlmI:b-kykg7y) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/c4918c1b8ea18824ac3f424bd3c34d9ae5ce588e/backend/api/views/user.py#L240)):*
> ```Python
>         """
>         try:
>             indy = User.objects.get(pk=int(pk))
> ```

replace this entire try block with

```user = self.get_object()```

DRF handles all of this for you in that function.
___
*[`backend/api/views/user.py` line 247 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrKwR5pB54JIOFUjTqp:-NrKwR5pB54JIOFUjTqq:b-sszy3p) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/c4918c1b8ea18824ac3f424bd3c34d9ae5ce588e/backend/api/views/user.py#L247)):*
> ```Python
>             )
> 
>         klass = Class.objects.get(
> ```

add this as validation in a custom serializer. let's do some pair programming.
___
*[`backend/api/views/user.py` line 261 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrKx2OqBHy3KjbU2aBx:-NrKx2OqBHy3KjbU2aBy:bg8dg1y) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/c4918c1b8ea18824ac3f424bd3c34d9ae5ce588e/backend/api/views/user.py#L261)):*
> ```Python
>             )
> 
>         if (
> ```

should be a serializer validation. let's do some pair programming.
___
*[`backend/api/views/user.py` line 295 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrKxNS1EJyER9BMza7H:-NrKxNS1EJyER9BMza7I:bg8dg1y) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/c4918c1b8ea18824ac3f424bd3c34d9ae5ce588e/backend/api/views/user.py#L295)):*
> ```Python
>         if request_accepted:
>             try:
>                 if not isinstance(request.data["first_name"], str):
> ```

should be a serializer validation. let's do some pair programming.
___
*[`backend/api/views/user.py` line 307 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrKxa6b0Nl3Q7vXPVLi:-NrKxa6b0Nl3Q7vXPVLj:bg8dg1y) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/c4918c1b8ea18824ac3f424bd3c34d9ae5ce588e/backend/api/views/user.py#L307)):*
> ```Python
> 
>             name = request.data["first_name"]
>             if self._is_name_unique_in_class(name, klass):
> ```

should be a serializer validation. let's do some pair programming.
___
*[`backend/api/views/user.py` line 313 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrKy21-DJ5ZGmkq7fnR:-NrKy21-DJ5ZGmkq7fnS:b-3n7hyr) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/c4918c1b8ea18824ac3f424bd3c34d9ae5ce588e/backend/api/views/user.py#L313)):*
> ```Python
>                 username = None
> 
>                 while (
> ```

let's make this a helper function on the StudentUser object so we're not repeating logic.

```StudentUser.generate_username()``


<!-- Sent from Reviewable.io -->

2024-02-23 15:30 UTC, faucomte97 reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308)* status: 13 of 16 files reviewed, 12 unresolved discussions (waiting on @SKairinos)

___
*[`backend/api/serializers/klass.py` line 104 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrKsh0H48DS8izM7mte:-NrL_Uyp4wrurjpaM3Ds:b-lz1lms) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/c4918c1b8ea18824ac3f424bd3c34d9ae5ce588e/backend/api/serializers/klass.py#L104)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

the problem with this update function is we are unable to update any other fields. let's discuss on call
</blockquote></details>

Don't we have the same problem with the other `update` functions then?
___
*[`backend/api/views/user.py` line 227 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrKvZRf1FFT6LcEco8B:-NrL__gx5dTd1oDPDmm6:bbckxzl) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/c4918c1b8ea18824ac3f424bd3c34d9ae5ce588e/backend/api/views/user.py#L227)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

pk is not optional. The url path won't match if pk is not provided. for example, it has to be

/api/users/1/handle-join-class-request
</blockquote></details>

Why did we make pk optional in the other custom actions then?


<!-- Sent from Reviewable.io -->

2024-02-23 15:33 UTC, faucomte97 reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308)* status: 13 of 16 files reviewed, 12 unresolved discussions (waiting on @SKairinos)

___
*[`backend/api/fixtures/independent_school_1_class_1_join_request.json` line 8 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrKrX2B5iM0wA-J9V1S:-NrL_rNwD27JmWihpY-e:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/c4918c1b8ea18824ac3f424bd3c34d9ae5ce588e/backend/api/fixtures/independent_school_1_class_1_join_request.json#L8)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

this is actually class 2 @ school 1. Please rename file accordingly.
</blockquote></details>

Done.
___
*[`backend/api/serializers/klass.py` line 105 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrKsM3UEuqa2MlNS1YA:-NrL_ujTBTNlG1TE2Ovt:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/c4918c1b8ea18824ac3f424bd3c34d9ae5ce588e/backend/api/serializers/klass.py#L105)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

comment not needed. the FE will be responsible for sending the datetime. if the user selects a number of hours, the FE will compute the final datetime (now + 3 hours) and send it the backend.
</blockquote></details>

Done.
___
*[`backend/api/views/user.py` line 53 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrKun1-2v8Su7_vPG-5:-NrLa3OADy0XYmT23krr:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/c4918c1b8ea18824ac3f424bd3c34d9ae5ce588e/backend/api/views/user.py#L53)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

delete this if. add the action name to the list above (in ["bulk", ...])
</blockquote></details>

Done.
___
*[`backend/api/views/user.py` line 232 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrKw-bR6_G97LUT0Tvq:-NrLa8f3Ce6iRJm0ciPS:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/c4918c1b8ea18824ac3f424bd3c34d9ae5ce588e/backend/api/views/user.py#L232)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

an admin in the
</blockquote></details>

Done.
___
*[`backend/api/views/user.py` line 240 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrKwDEZ87B79GVzBlmH:-NrLaFpT9m0_wc0NLiwr:blyihk2) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/c4918c1b8ea18824ac3f424bd3c34d9ae5ce588e/backend/api/views/user.py#L240)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

replace this entire try block with

```user = self.get_object()```

DRF handles all of this for you in that function.
</blockquote></details>

Why don't we do that in the `reset_password` action then?


<!-- Sent from Reviewable.io -->

2024-02-28 17:06 UTC, faucomte97 reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308)* status: 8 of 17 files reviewed, 12 unresolved discussions (waiting on @faucomte97 and @SKairinos)

___
*[`backend/api/views/user.py` line 247 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrKwR5pB54JIOFUjTqp:-NrkfXHsA1oN1jz_OVwh:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/c4918c1b8ea18824ac3f424bd3c34d9ae5ce588e/backend/api/views/user.py#L247)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

add this as validation in a custom serializer. let's do some pair programming.
</blockquote></details>

Done.
___
*[`backend/api/views/user.py` line 261 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrKx2OqBHy3KjbU2aBx:-NrkfXil2f-SmjdgM0RP:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/c4918c1b8ea18824ac3f424bd3c34d9ae5ce588e/backend/api/views/user.py#L261)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

should be a serializer validation. let's do some pair programming.
</blockquote></details>

Done.
___
*[`backend/api/views/user.py` line 295 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrKxNS1EJyER9BMza7H:-NrkfYB4Cby-hxrm6Lnj:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/c4918c1b8ea18824ac3f424bd3c34d9ae5ce588e/backend/api/views/user.py#L295)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

should be a serializer validation. let's do some pair programming.
</blockquote></details>

Done.
___
*[`backend/api/views/user.py` line 307 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrKxa6b0Nl3Q7vXPVLi:-NrkfYn06-sqYHvwVaxJ:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/c4918c1b8ea18824ac3f424bd3c34d9ae5ce588e/backend/api/views/user.py#L307)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

should be a serializer validation. let's do some pair programming.
</blockquote></details>

Done.
___
*[`backend/api/views/user.py` line 313 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrKy21-DJ5ZGmkq7fnR:-NrkfZ2Y1azSimAqFDTr:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/c4918c1b8ea18824ac3f424bd3c34d9ae5ce588e/backend/api/views/user.py#L313)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

let's make this a helper function on the StudentUser object so we're not repeating logic.

```StudentUser.generate_username()``
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-29 13:03 UTC, SKairinos requested changes
> Reviewed 4 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308)* status: 12 of 17 files reviewed, 35 unresolved discussions (waiting on @faucomte97)

___
*[`backend/Pipfile` line 10 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrogGiiBXGN5NOPquaN:-NrogGiiBXGN5NOPquaO:b-bm5ozc) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/51d90bc1070b60368bc85d56dc0179d8a3520181/backend/Pipfile#L10)):*
> ```TOML
> #   https://github.com/ocadotechnology/codeforlife-package-python/blob/{ref}/Pipfile
> # Replace "{ref}" in the above URL with the ref set below.
> codeforlife = {ref = "fixtures_fix", git = "https://github.com/ocadotechnology/codeforlife-package-python.git"}
> ```

replace with latest version
___
*[`backend/Pipfile` line 37 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrogLEXAWzrps7Rg-1J:-NrogLEXAWzrps7Rg-1K:b-bm5ozc) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/51d90bc1070b60368bc85d56dc0179d8a3520181/backend/Pipfile#L37)):*
> ```TOML
> #   https://github.com/ocadotechnology/codeforlife-package-python/blob/{ref}/Pipfile
> # Replace "{ref}" in the above URL with the ref set below.
> codeforlife = {ref = "fixtures_fix", git = "https://github.com/ocadotechnology/codeforlife-package-python.git", extras = ["dev"]}
> ```

replace with latest version
___
*[`backend/api/serializers/user.py` line 96 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-Nrog_616bXOZJ-eJ7dE:-Nrog_616bXOZJ-eJ7dF:bzaibps) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/51d90bc1070b60368bc85d56dc0179d8a3520181/backend/api/serializers/user.py#L96)):*
> ```Python
>     teacher = TeacherSerializer(source="new_teacher", required=False)
>     requesting_to_join_class = serializers.CharField(
>         required=False, allow_blank=True
> ```

instead of allow_blank=True, rather don't allow blank but make it nullable. If you're not requesting to join a class, it will be null. Let's generally agree to use null to mean "no value" for all fields (so not "" for char fields).
___
*[`backend/api/serializers/user.py` line 134 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrosdZT2d29tG6KjrMr:-NrosdZT2d29tG6KjrMs:b-bi7k9e) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/51d90bc1070b60368bc85d56dc0179d8a3520181/backend/api/serializers/user.py#L134)):*
> ```Python
>             if self.instance.teacher:
>                 if "last_name" in attrs and not attrs["last_name"]:
>                     raise serializers.ValidationError(
> ```

any errors that you reuse should be saved in a variable

```py
last_name_required_error = serializers.ValidationError(
    "Last name is required.", code="last_name_required"
 )
...
raise last_name_required_error
```
___
*[`backend/api/serializers/user.py` line 139 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrotsQA-ELmbc_vuAF3:-NrotsQA-ELmbc_vuAF4:bptz677) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/51d90bc1070b60368bc85d56dc0179d8a3520181/backend/api/serializers/user.py#L139)):*
> ```Python
> 
>                 if "requesting_to_join_class" in attrs:
>                     raise serializers.ValidationError(
> ```

any errors that you reuse should be saved in a variable
___
*[`backend/api/serializers/user.py` line 146 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-Nrou2xIAfDcOTs8AEbG:-Nrou2xIAfDcOTs8AEbH:b-aeafzk) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/51d90bc1070b60368bc85d56dc0179d8a3520181/backend/api/serializers/user.py#L146)):*
> ```Python
>             if self.instance.student:
>                 if self.view.action != "reset_password":
>                     if self.request.student_user.pk != self.instance.pk:
> ```

should not check this here. instead, in get_queryset() you should filter/exclude the instances. The instance passed to the serializer should come from the valid-queryset. Therefore, there's no need to do this validation in the serializer. Let me know if I missed something.
___
*[`backend/api/serializers/user.py` line 159 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NroucWmCnat6G6H5MxK:-NroucWmCnat6G6H5MxL:bptz677) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/51d90bc1070b60368bc85d56dc0179d8a3520181/backend/api/serializers/user.py#L159)):*
> ```Python
>                     and "class_field" in attrs["new_student"]
>                 ):
>                     raise serializers.ValidationError(
> ```

any errors that you reuse should be saved in a variable
___
*[`backend/api/serializers/user.py` line 165 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrorKwg7XjPuNcWJYiR:-NrorKwg7XjPuNcWJYiS:b-tc0fmi) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/51d90bc1070b60368bc85d56dc0179d8a3520181/backend/api/serializers/user.py#L165)):*
> ```Python
>                     )
> 
>         else:  # Creating
> ```

please add this validation here

```py
if "new_teacher" in attrs and "new_student" in attrs:
    raise serializers.ValidationError("...", code="teacher_and_student")
```

feel free to set whatever message and code you feel appropriate
___
*[`backend/api/serializers/user.py` line 167 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrooT0c4ZE3QlTQ4SnF:-NrooT0c4ZE3QlTQ4SnG:bamqyqi) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/51d90bc1070b60368bc85d56dc0179d8a3520181/backend/api/serializers/user.py#L167)):*
> ```Python
>         else:  # Creating
>             if "new_teacher" in attrs:
>                 if "last_name" not in attrs or attrs["last_name"] is None:
> ```

can just simplify to `not attrs.get("last_name")`. keep in mind last_name != "" also. you are only checking None in your code.
___
*[`backend/api/serializers/user.py` line 169 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-Nroq_N23xhlIySRkkso:-Nroq_N23xhlIySRkksp:b-ts4hti) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/51d90bc1070b60368bc85d56dc0179d8a3520181/backend/api/serializers/user.py#L169)):*
> ```Python
>                 if "last_name" not in attrs or attrs["last_name"] is None:
>                     raise serializers.ValidationError(
>                         "Last name is required.", code="last_name_required"
> ```

side note (nothing to do) here we do need to prefix the code with "last_name" because we are raising from inside validate().
___
*[`backend/api/serializers/user.py` line 178 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NroqzyD2t3lD7l3VSgV:-NroqzyD2t3lD7l3VSgW:bkgnhht) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/51d90bc1070b60368bc85d56dc0179d8a3520181/backend/api/serializers/user.py#L178)):*
> ```Python
>                     )
> 
>             if "new_student" in attrs:
> ```

should be in elif since you can only be a teacher or an independent
___
*[`backend/api/serializers/user.py` line 211 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-Nronou72lfvnQFgXzZd:-Nronou72lfvnQFgXzZe:btyb89n) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/51d90bc1070b60368bc85d56dc0179d8a3520181/backend/api/serializers/user.py#L211)):*
> ```Python
> 
>     def validate_requesting_to_join_class(self, value: str):
>         # NOTE: Error message is purposefully ambiguous to prevent class
> ```

Why does it matter if they can enumerate classes? It's not sensitive data (unlike email addresses)
___
*[`backend/api/serializers/user.p [...]

2024-02-29 15:34 UTC, faucomte97 reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308)* status: 10 of 17 files reviewed, 35 unresolved discussions (waiting on @faucomte97 and @SKairinos)

___
*[`backend/Pipfile` line 10 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrogGiiBXGN5NOPquaN:-Nrp4gc-1mJNUAAqAVLA:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/51d90bc1070b60368bc85d56dc0179d8a3520181/backend/Pipfile#L10)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

replace with latest version
</blockquote></details>

Done.
___
*[`backend/Pipfile` line 37 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrogLEXAWzrps7Rg-1J:-Nrp4gsP0PBlR-t-qC_l:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/51d90bc1070b60368bc85d56dc0179d8a3520181/backend/Pipfile#L37)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

replace with latest version
</blockquote></details>

Done.
___
*[`backend/api/serializers/user.py` line 96 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-Nrog_616bXOZJ-eJ7dE:-NrpJxDA8J-c4q8ntci-:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/51d90bc1070b60368bc85d56dc0179d8a3520181/backend/api/serializers/user.py#L96)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

instead of allow_blank=True, rather don't allow blank but make it nullable. If you're not requesting to join a class, it will be null. Let's generally agree to use null to mean "no value" for all fields (so not "" for char fields).
</blockquote></details>

Done.
___
*[`backend/api/serializers/user.py` line 134 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrosdZT2d29tG6KjrMr:-NrpBhnz4Hx9x1GMClnt:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/51d90bc1070b60368bc85d56dc0179d8a3520181/backend/api/serializers/user.py#L134)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

any errors that you reuse should be saved in a variable

```py
last_name_required_error = serializers.ValidationError(
    "Last name is required.", code="last_name_required"
 )
...
raise last_name_required_error
```
</blockquote></details>

Done.
___
*[`backend/api/serializers/user.py` line 139 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrotsQA-ELmbc_vuAF3:-NrpBsZUAV19_aD2-q5t:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/51d90bc1070b60368bc85d56dc0179d8a3520181/backend/api/serializers/user.py#L139)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

any errors that you reuse should be saved in a variable
</blockquote></details>

Done.
___
*[`backend/api/serializers/user.py` line 146 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-Nrou2xIAfDcOTs8AEbG:-NrpVBH3DDW2Z9k4feEF:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/51d90bc1070b60368bc85d56dc0179d8a3520181/backend/api/serializers/user.py#L146)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

should not check this here. instead, in get_queryset() you should filter/exclude the instances. The instance passed to the serializer should come from the valid-queryset. Therefore, there's no need to do this validation in the serializer. Let me know if I missed something.
</blockquote></details>

Done.
___
*[`backend/api/serializers/user.py` line 159 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NroucWmCnat6G6H5MxK:-NrpCAgA0WApMjQ370gO:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/51d90bc1070b60368bc85d56dc0179d8a3520181/backend/api/serializers/user.py#L159)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

any errors that you reuse should be saved in a variable
</blockquote></details>

Done.
___
*[`backend/api/serializers/user.py` line 165 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrorKwg7XjPuNcWJYiR:-NrpCXHM33FaWd9uk_Ht:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/51d90bc1070b60368bc85d56dc0179d8a3520181/backend/api/serializers/user.py#L165)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

please add this validation here

```py
if "new_teacher" in attrs and "new_student" in attrs:
    raise serializers.ValidationError("...", code="teacher_and_student")
```

feel free to set whatever message and code you feel appropriate
</blockquote></details>

Done.
___
*[`backend/api/serializers/user.py` line 167 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrooT0c4ZE3QlTQ4SnF:-NrpDRQtEJ6ZCZNejLVb:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/51d90bc1070b60368bc85d56dc0179d8a3520181/backend/api/serializers/user.py#L167)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

can just simplify to `not attrs.get("last_name")`. keep in mind last_name != "" also. you are only checking None in your code.
</blockquote></details>

Done.
___
*[`backend/api/serializers/user.py` line 169 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-Nroq_N23xhlIySRkkso:-NrpDTl16PtItvcgolrq:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/51d90bc1070b60368bc85d56dc0179d8a3520181/backend/api/serializers/user.py#L169)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

side note (nothing to do) here we do need to prefix the code with "last_name" because we are raising from inside validate().
</blockquote></details>

Done.
___
*[`backend/api/serializers/user.py` line 178 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NroqzyD2t3lD7l3VSgV:-NrpDj-2-qLqn3YYkIhe:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/51d90bc1070b60368bc85d56dc0179d8a3520181/backend/api/serializers/user.py#L178)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

should be in elif since you can only be a teacher or an independent
</blockquote></details>

Done.
___
*[`backend/api/serializers/user.py` line 211 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-Nronou72lfvnQFgXzZd:-NrpDjcW59c7R5a6WKbr:bkvtkkh) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/51d90bc1070b60368bc85d56dc0179d8a3520181/backend/api/serializers/user.py#L211)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

Why does it matter if they can enumerate classes? It's not sensitive data (unlike email addresses)
</blockquote></details>

You're right but class codes are used to login and enumerating existing class codes means attackers can reduce the range of login details used to brute force login.
___
*[`backend/api/serializers/user.py` line 213 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-Nroms4d0zMyPZyrxCrK:-NrpDt9Z25ipcMWF4g4t:bkm1mmt) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/51d90bc1070b60368bc85d56dc0179d8a3520181/backend/api/serializers/user.py#L213)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

(don't make these changes until we discuss the above question)

replace these 2 lines with
```py
error = serializers.Valid [...]

2024-03-05 10:02 UTC, SKairinos requested changes
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308)* status: 9 of 17 files reviewed, 25 unresolved discussions (waiting on @faucomte97)

___
*[`backend/api/serializers/user.py` line 213 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-Nroms4d0zMyPZyrxCrK:-NsD2mOG19kUP8UamLsy:b-mk94em) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/51d90bc1070b60368bc85d56dc0179d8a3520181/backend/api/serializers/user.py#L213)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

still need to make error a reusable variable
</blockquote></details>

actually, although the error message is reusable, the code is not. The code should be unique for each error scenario. then, please assert each code in the tests. error codes are for internal use only so it's not a security risk.
___
*[`backend/api/serializers/user.py` line 126 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsCvP2s9CBCFe01mkT0:-NsCvP2s9CBCFe01mkT1:b-fzef4s) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/2163f47d458bd5ede4698e4bb032bcfda54fec80/backend/api/serializers/user.py#L126)):*
> ```Python
>     def validate(self, attrs):
>         last_name_required_error = serializers.ValidationError(
>             "Last name is required.", code="last_name_required"
> ```

error_code="last_name__required"

since we're in the general validate(), we should make the error code follow the naming convention:

"{field_name}__{error_code}"

in theory, if we were raising this error inside validate_last_name(), the error code could just be "required"
___
*[`backend/api/serializers/user.py` line 129 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrpZXgl15laXBuEYqYe:-NsCw9EAD3gjTSVms4gx:b-rvla0y) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/2163f47d458bd5ede4698e4bb032bcfda54fec80/backend/api/serializers/user.py#L129)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

make var name match code
</blockquote></details>

also error code should following naming convention = "requesting_to_join_class__teacher". In other words, the error is that a teacher is requesting to join a class.

var name should be "requesting_to_join_class__teacher_error"
___
*[`backend/api/serializers/user.py` line 137 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-Ns9QT_2ClUldwr99tTu:-NsCwwysDigFsBKTdDSb:b-kz8zl9) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/2163f47d458bd5ede4698e4bb032bcfda54fec80/backend/api/serializers/user.py#L137)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

make var name match code
</blockquote></details>

also error code should following naming convention = "requesting_to_join_class__student". In other words, the error is that a student is requesting to join a class.

var name should be "requesting_to_join_class__student_error"
___
*[`backend/api/serializers/user.py` line 147 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsCsCsL3PpUB2Br2Abq:-NsCsCsL3PpUB2Br2Abr:b-xhi1in) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/2163f47d458bd5ede4698e4bb032bcfda54fec80/backend/api/serializers/user.py#L147)):*
> ```Python
> 
>             if self.instance.teacher:
>                 if "last_name" in attrs and not attrs["last_name"]:
> ```

on second thought, there's no need to do this check. we've already specified last_name must have a min_length=1 and last_name is not a nullable field. the error probably isn't reused anymore so we can just put it inline below. 
___
*[`backend/api/serializers/user.py` line 153 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsCsvx_5CBO18i69Z9N:-NsCsvx_5CBO18i69Z9O:b-i5ers8) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/2163f47d458bd5ede4698e4bb032bcfda54fec80/backend/api/serializers/user.py#L153)):*
> ```Python
>                     raise teacher_cannot_request_join_class_error
> 
>             if self.instance.student:
> ```

make elif. can only be teacher or student - no need to check both
___
*[`backend/api/tests/serializers/test_user.py` line 82 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsCtWWL6rqI2LswnfBa:-NsCtWWL6rqI2LswnfBb:bhlq05m) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/2163f47d458bd5ede4698e4bb032bcfda54fec80/backend/api/tests/serializers/test_user.py#L82)):*
> ```Python
>         )
> 
>     def test_validate__teacher__first_name_required(self):
> ```

rename to "test_validate__create__teacher__last_name_required"
you are testing:
1. the validate func
2. when a user is created
3. when a teacher-user is created
4. a teacher-user's last name is required during creation (this must be the exact error code)

please update all the validate test names to have the same naming convention.

"test_validate__{create/update}__{user_type}__{error_code}"
___
*[`backend/api/tests/serializers/test_user.py` line 83 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsCu5ry4jj_4MwAlcvE:-NsCu5ry4jj_4MwAlcvF:b-bnv01u) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/2163f47d458bd5ede4698e4bb032bcfda54fec80/backend/api/tests/serializers/test_user.py#L83)):*
> ```Python
> 
>     def test_validate__teacher__first_name_required(self):
>         """Teacher must have a first name"""
> ```

Not fully describing the test case. Something like:

"""Teacher-user's last_name is required during creation."""

Also, you said first name. You meant last name.

Please update all test docstring to fully describe the test case.
___
*[`backend/api/tests/serializers/test_user.py` line 89 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsCv-c-4OvImi7V_v3P:-NsCv-c-4OvImi7V_v3Q:b-sqmlxw) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/2163f47d458bd5ede4698e4bb032bcfda54fec80/backend/api/tests/serializers/test_user.py#L89)):*
> ```Python
> 
>     def test_validate__teacher__requesting_to_join_class_forbidden(self):
>         """Teacher cannot request to join a class"""
> ```

see above comment about test naming convention and docstring missing details
___
*[`backend/api/tests/serializers/test_user.py` line 102 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsCv5FW0fdMhoqQmsC2:-NsCv5FW0fdMhoqQmsC3:b-fbx038) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/2163f47d458bd5ede4698e4bb032bcfda54fec80/backend/api/tests/serializers/test_user.py#L102)):*
> ```Python
>         self,
>     ):
>         """Student cannot have both requesting_to_join_class and class_field"""
> ```

see above comment about test naming convention and docstring missing details. Also, describe the test case/scenario rather than how it's implemented. For example:

"Student-user cannot request to join a class." 
___
*[`backend/api/tests/serializers/test_user.py` line 112 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsD1PST6P0OSSxhbFMO:-NsD1PST6P0OSSxhbFMP:b-sqmlxw) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/2163f47d458bd5ede4698e4bb032bcfda54fec80/backend/api/tests/serializers/test_user.py#L112)):*
> ```Python
> 
>     def test_validate_requesting_to_join_class__does_not_exist(self):
>         """Join class request cannot be for a class that doesn't exist"""
> ```

see above comment about test naming convention and docstring missing details
___
*[`backend/api/tests/serializers/test_user.py` line 121 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308# [...]

2024-03-05 17:22 UTC, faucomte97 reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308)* status: 9 of 17 files reviewed, 25 unresolved discussions (waiting on @faucomte97 and @SKairinos)

___
*[`backend/api/serializers/user.py` line 213 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-Nroms4d0zMyPZyrxCrK:-NsEXSDD6JJthCqXPooR:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/51d90bc1070b60368bc85d56dc0179d8a3520181/backend/api/serializers/user.py#L213)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

actually, although the error message is reusable, the code is not. The code should be unique for each error scenario. then, please assert each code in the tests. error codes are for internal use only so it's not a security risk.
</blockquote></details>

Done.
___
*[`backend/api/serializers/user.py` line 126 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsCvP2s9CBCFe01mkT0:-NsEWAyTCz6eDN6Jp9Gx:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/2163f47d458bd5ede4698e4bb032bcfda54fec80/backend/api/serializers/user.py#L126)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

error_code="last_name__required"

since we're in the general validate(), we should make the error code follow the naming convention:

"{field_name}__{error_code}"

in theory, if we were raising this error inside validate_last_name(), the error code could just be "required"
</blockquote></details>

Done.
___
*[`backend/api/serializers/user.py` line 129 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NrpZXgl15laXBuEYqYe:-NsEWBBj9ikKeg9guQWX:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/2163f47d458bd5ede4698e4bb032bcfda54fec80/backend/api/serializers/user.py#L129)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

also error code should following naming convention = "requesting_to_join_class__teacher". In other words, the error is that a teacher is requesting to join a class.

var name should be "requesting_to_join_class__teacher_error"
</blockquote></details>

Done.
___
*[`backend/api/serializers/user.py` line 137 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-Ns9QT_2ClUldwr99tTu:-NsEWIa30sCF3k3CZlDy:bmhzvrf) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/2163f47d458bd5ede4698e4bb032bcfda54fec80/backend/api/serializers/user.py#L137)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

also error code should following naming convention = "requesting_to_join_class__student". In other words, the error is that a student is requesting to join a class.

var name should be "requesting_to_join_class__student_error"
</blockquote></details>

The error isn't strictly that a student is requesting to join a class, the error is that a student who already is in a class is requesting to join a class *or* that a student who is requesting to join a class is being edited to now be in a class. Not sure what name to give then
___
*[`backend/api/serializers/user.py` line 147 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsCsCsL3PpUB2Br2Abq:-NsEWmcwDgWOk11T02CY:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/2163f47d458bd5ede4698e4bb032bcfda54fec80/backend/api/serializers/user.py#L147)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

on second thought, there's no need to do this check. we've already specified last_name must have a min_length=1 and last_name is not a nullable field. the error probably isn't reused anymore so we can just put it inline below.
</blockquote></details>

Done.
___
*[`backend/api/serializers/user.py` line 153 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsCsvx_5CBO18i69Z9N:-NsEWvKrB7n4OVc4YG-P:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/2163f47d458bd5ede4698e4bb032bcfda54fec80/backend/api/serializers/user.py#L153)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

make elif. can only be teacher or student - no need to check both
</blockquote></details>

Done.
___
*[`backend/api/tests/serializers/test_user.py` line 82 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsCtWWL6rqI2LswnfBa:-NsE_L-u43MPg7pkrsIT:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/2163f47d458bd5ede4698e4bb032bcfda54fec80/backend/api/tests/serializers/test_user.py#L82)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

rename to "test_validate__create__teacher__last_name_required"
you are testing:
1. the validate func
2. when a user is created
3. when a teacher-user is created
4. a teacher-user's last name is required during creation (this must be the exact error code)

please update all the validate test names to have the same naming convention.

"test_validate__{create/update}__{user_type}__{error_code}"
</blockquote></details>

Done.
___
*[`backend/api/tests/serializers/test_user.py` line 83 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsCu5ry4jj_4MwAlcvE:-NsE_LZZ3U7jjw9eM7cI:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/2163f47d458bd5ede4698e4bb032bcfda54fec80/backend/api/tests/serializers/test_user.py#L83)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

Not fully describing the test case. Something like:

"""Teacher-user's last_name is required during creation."""

Also, you said first name. You meant last name.

Please update all test docstring to fully describe the test case.
</blockquote></details>

Done.
___
*[`backend/api/tests/serializers/test_user.py` line 89 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsCv-c-4OvImi7V_v3P:-NsEaEsh5vzpmgZpN1Xh:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/2163f47d458bd5ede4698e4bb032bcfda54fec80/backend/api/tests/serializers/test_user.py#L89)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

see above comment about test naming convention and docstring missing details
</blockquote></details>

Done.
___
*[`backend/api/tests/serializers/test_user.py` line 102 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsCv5FW0fdMhoqQmsC2:-NsEaL67BAcwSLany-D2:bdd22ek) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/2163f47d458bd5ede4698e4bb032bcfda54fec80/backend/api/tests/serializers/test_user.py#L102)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

see above comment about test naming convention and docstring missing details. Also, describe the test case/scenario rather than how it's implemented. For example:

"Student-user cannot request to join a class."
</blockquote></details>

See my reply above about specifics of error
___
*[`backend/api/tests/serializers/test_user.py` line 112 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsD1PST6P0OSSxhbFMO:-NsEbX4HC0IxK4GZulbY:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/2163f47d458bd5ede4698e4bb032bcfda54fec80/backend/api/tests/serializers/test_user.py#L112)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

see above comment about test naming convention and docstring missing details
</blockquote></details>

Done.
___
*[`b [...]

2024-03-07 12:48 UTC, SKairinos requested changes
> Reviewed 1 of 9 files at r2, 6 of 10 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308)* status: all files reviewed, 19 unresolved discussions (waiting on @faucomte97)

___
*[`backend/Pipfile` line 26 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsNf5H442NB7pA6syHi:-NsNf5H442NB7pA6syHj:bnmmekf) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/579f2c18557ecf4147b1a35478f7844f24436788/backend/Pipfile#L26)):*
> ```TOML
> 
> [packages]
> codeforlife = {ref = "v0.14.5", git = "https://github.com/ocadotechnology/codeforlife-package-python.git"}
> ```

use the l
___
*[`backend/api/serializers/user.py` line 137 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-Ns9QT_2ClUldwr99tTu:-NsNQbPLELqaWr0ToNFE:beuzody) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/2163f47d458bd5ede4698e4bb032bcfda54fec80/backend/api/serializers/user.py#L137)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

The error isn't strictly that a student is requesting to join a class, the error is that a student who already is in a class is requesting to join a class *or* that a student who is requesting to join a class is being edited to now be in a class. Not sure what name to give then
</blockquote></details>

remember that we agreed "student" would mean a user that's a school/class student. For a student that's not in a class/school, we refer to them as "independent". Therefore, the error code "requesting_to_join_class__student" is the correct one because it means a [school/class] student is requesting to join a class.

also, as per our convo, never reuse error codes. I suggest codes:
"requesting_to_join_class__student__create"
"requesting_to_join_class__student__update" 
___
*[`backend/api/serializers/user.py` line 127 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsNhIMD3FZWFvOEzhqp:-NsNhIMD3FZWFvOEzhqq:btyf8x3) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/579f2c18557ecf4147b1a35478f7844f24436788/backend/api/serializers/user.py#L127)):*
> ```Python
>         requesting_to_join_class__teacher_error = serializers.ValidationError(
>             "Teacher can't request to join a class.",
>             code="requesting_to_join_class__teacher",
> ```

as per our convo, never reuse error codes. I suggest codes:
"requesting_to_join_class__teacher__create"
"requesting_to_join_class__teacher__update" 
___
*[`backend/api/serializers/user.py` line 147 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsNhgYX3rADrRykeUqi:-NsNhgYX3rADrRykeUqj:b-f5z2q5) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/579f2c18557ecf4147b1a35478f7844f24436788/backend/api/serializers/user.py#L147)):*
> ```Python
> 
>             elif self.instance.student:
>                 if (
> ```

as per our convo, never reuse error codes. since these are two different scenarios, I suggest codes:
"requesting_to_join_class__student__update__in_class"
"requesting_to_join_class__student__update__requesting_to_join_class"

That way we can assert the 2 different scenarios with distinct codes. 
___
*[`backend/api/tests/serializers/test_user.py` line 82 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsCtWWL6rqI2LswnfBa:-NsNTH7pAcOWPfazWupA:bjnwc8w) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/2163f47d458bd5ede4698e4bb032bcfda54fec80/backend/api/tests/serializers/test_user.py#L82)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

small fix, since the error code is "last_name__required", the test name should be:

"test_validate__create__teacher__last_name__required"

Naming convention = "test_validate\_\_{create/update}\_\_{user_type}\_\_{error_code}"

fix all test names below 
___
*[`backend/api/tests/serializers/test_user.py` line 89 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsCv-c-4OvImi7V_v3P:-NsNTePM5nkDQPmZTEQN:b-dj9ojk) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/2163f47d458bd5ede4698e4bb032bcfda54fec80/backend/api/tests/serializers/test_user.py#L89)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

small fix, since the error code is "requesting_to_join_class__teacher", the test name should be:

"test_validate__create__teacher__requesting_to_join_class__teacher"

Naming convention = "test_validate\_\_{create/update}\_\_{user_type}\_\_{error_code}"

fix all test names below 
___
*[`backend/api/tests/serializers/test_user.py` line 102 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsCv5FW0fdMhoqQmsC2:-NsNVDe91jZBHFgolyAB:bw9f64s) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/2163f47d458bd5ede4698e4bb032bcfda54fec80/backend/api/tests/serializers/test_user.py#L102)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

See my reply above about specifics of error
</blockquote></details>

see my response and above comment about naming convention
___
*[`backend/api/tests/serializers/test_user.py` line 103 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsNUjO-0p8Ky-5THqWD:-NsNUjO-0p8Ky-5THqWE:b-vwlf9c) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/579f2c18557ecf4147b1a35478f7844f24436788/backend/api/tests/serializers/test_user.py#L103)):*
> ```Python
>         )
> 
>     def test_validate__update__teacher__requesting_to_join_class(self):
> ```

see above comment about naming convention
___
*[`backend/api/tests/serializers/test_user.py` line 209 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsNYuWxC9ymcjWrjx4U:-NsNYuWxC9ymcjWrjx4V:btqdozf) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/579f2c18557ecf4147b1a35478f7844f24436788/backend/api/tests/serializers/test_user.py#L209)):*
> ```Python
>         """Cannot accept a new student into a class with a duplicate name."""
>         user_fields = (
>             StudentUser.objects.filter(new_student__class_field=self.class_1)
> ```

should be: new_student__class_field=self.indy_user.student.pending_class_request

you specifically want whatever class the indy user is requesting to join.

I understand that class_1 implicitly is the same class. But should be explicit reference, not implicit.

This is important for 2 reasons:
1. readability - i don't know class_1 is the class the indy user is requesting to join unless I go and read the fixtures (I shouldn't need to do this)
2. maintainability - if we ever decide to change the fixtures in the future, this implicit reference will break. An explicit one won't.
___
*[`backend/api/tests/views/test_user.py` line 125 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsN_dnp6k5yzjo7LI5H:-NsN_dnp6k5yzjo7LI5I:b-p0ivw8) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/579f2c18557ecf4147b1a35478f7844f24436788/backend/api/tests/views/test_user.py#L125)):*
> ```Python
>         )
> 
>     def test_get_permissions__handle_join_class_request(self):
> ```

name should be "test_get_permissions\_\_independents\_\_handle_join_class_request"

Naming convention: "test_get_permissions__{action}"
___
*[`backend/api/tests/views/test_user.py` line 171 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsNbDmr57CgZflANSQ8:-NsNbDmr57CgZflANSQ9:ba2ac5t) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/579f2c18557ecf4147b1a354 [...]

2024-03-07 17:44 UTC, faucomte97 reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308)* status: all files reviewed, 18 unresolved discussions (waiting on @SKairinos)

___
*[`backend/Pipfile` line 26 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsNf5H442NB7pA6syHi:-NsOIfX4D79HISEhDJmA:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/579f2c18557ecf4147b1a35478f7844f24436788/backend/Pipfile#L26)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

use the l
</blockquote></details>

Done.
___
*[`backend/api/serializers/user.py` line 137 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-Ns9QT_2ClUldwr99tTu:-NsOEAU-2TXcHv7lv-71:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/2163f47d458bd5ede4698e4bb032bcfda54fec80/backend/api/serializers/user.py#L137)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

remember that we agreed "student" would mean a user that's a school/class student. For a student that's not in a class/school, we refer to them as "independent". Therefore, the error code "requesting_to_join_class__student" is the correct one because it means a [school/class] student is requesting to join a class.

also, as per our convo, never reuse error codes. I suggest codes:
"requesting_to_join_class__student__create"
"requesting_to_join_class__student__update"
</blockquote></details>

Done.
___
*[`backend/api/serializers/user.py` line 127 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsNhIMD3FZWFvOEzhqp:-NsOB-YF0qHym60Zmf9Z:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/579f2c18557ecf4147b1a35478f7844f24436788/backend/api/serializers/user.py#L127)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

as per our convo, never reuse error codes. I suggest codes:
"requesting_to_join_class__teacher__create"
"requesting_to_join_class__teacher__update"
</blockquote></details>

Done.
___
*[`backend/api/serializers/user.py` line 147 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsNhgYX3rADrRykeUqi:-NsOEAo_AevJ3GaCqPBp:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/579f2c18557ecf4147b1a35478f7844f24436788/backend/api/serializers/user.py#L147)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

as per our convo, never reuse error codes. since these are two different scenarios, I suggest codes:
"requesting_to_join_class__student__update__in_class"
"requesting_to_join_class__student__update__requesting_to_join_class"

That way we can assert the 2 different scenarios with distinct codes.
</blockquote></details>

Done.
___
*[`backend/api/tests/serializers/test_user.py` line 82 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsCtWWL6rqI2LswnfBa:-NsOEbpV4Dq5rVhB1yOB:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/2163f47d458bd5ede4698e4bb032bcfda54fec80/backend/api/tests/serializers/test_user.py#L82)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

small fix, since the error code is "last_name__required", the test name should be:

"test_validate__create__teacher__last_name__required"

Naming convention = "test_validate\_\_{create/update}\_\_{user_type}\_\_{error_code}"

fix all test names below
</blockquote></details>

Done.
___
*[`backend/api/tests/serializers/test_user.py` line 89 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsCv-c-4OvImi7V_v3P:-NsOEh1JD3o-P16MsqkJ:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/2163f47d458bd5ede4698e4bb032bcfda54fec80/backend/api/tests/serializers/test_user.py#L89)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

small fix, since the error code is "requesting_to_join_class__teacher", the test name should be:

"test_validate__create__teacher__requesting_to_join_class__teacher"

Naming convention = "test_validate\_\_{create/update}\_\_{user_type}\_\_{error_code}"

fix all test names below
</blockquote></details>

Done.
___
*[`backend/api/tests/serializers/test_user.py` line 102 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsCv5FW0fdMhoqQmsC2:-NsOHG9K0cCAjb8ZDAtN:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/2163f47d458bd5ede4698e4bb032bcfda54fec80/backend/api/tests/serializers/test_user.py#L102)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

see my response and above comment about naming convention
</blockquote></details>

Done.
___
*[`backend/api/tests/serializers/test_user.py` line 103 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsNUjO-0p8Ky-5THqWD:-NsOGHGt1bgWsbJaqYH0:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/579f2c18557ecf4147b1a35478f7844f24436788/backend/api/tests/serializers/test_user.py#L103)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

see above comment about naming convention
</blockquote></details>

Done.
___
*[`backend/api/tests/serializers/test_user.py` line 209 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsNYuWxC9ymcjWrjx4U:-NsOH_rB6We_TSVGXPlQ:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/579f2c18557ecf4147b1a35478f7844f24436788/backend/api/tests/serializers/test_user.py#L209)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

should be: new_student__class_field=self.indy_user.student.pending_class_request

you specifically want whatever class the indy user is requesting to join.

I understand that class_1 implicitly is the same class. But should be explicit reference, not implicit.

This is important for 2 reasons:
1. readability - i don't know class_1 is the class the indy user is requesting to join unless I go and read the fixtures (I shouldn't need to do this)
2. maintainability - if we ever decide to change the fixtures in the future, this implicit reference will break. An explicit one won't.
</blockquote></details>

Done.
___
*[`backend/api/tests/views/test_user.py` line 125 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsN_dnp6k5yzjo7LI5H:-NsOHknC34dnKAUb18FR:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/579f2c18557ecf4147b1a35478f7844f24436788/backend/api/tests/views/test_user.py#L125)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

name should be "test_get_permissions\_\_independents\_\_handle_join_class_request"

Naming convention: "test_get_permissions__{action}"
</blockquote></details>

Done.
___
*[`backend/api/tests/views/test_user.py` line 171 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsNbDmr57CgZflANSQ8:-NsOHt2S7IwezdStnwtc:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/579f2c18557ecf4147b1a35478f7844f24436788/backend/api/tests/views/test_user.py#L171)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

instead, pass in the user.

user: SchoolTeacherUser
</blockquote></details>

Done.
___
*[`backend/api/tests/views/test_user.py` line 173 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308#-NsNj89j-zcjWaIf-e5L:-NsOI-5U2U19Jkf_SGT0:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blo [...]

2024-03-08 08:33 UTC, SKairinos approved these changes
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/308)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @faucomte97)



<!-- Sent from Reviewable.io -->

2024-03-08 08:33 UTC, merged