Bulk transfer students
ocadotechnology/codeforlife-portal-react pull request #311
Opened 2024-02-27 11:28 UTC by SKairinos

2024-03-01 12:30 UTC, faucomte97 requested changes
> Reviewed 7 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311)* status: 7 of 16 files reviewed, 1 unresolved discussion (waiting on @SKairinos)

___
*[`backend/Pipfile` line 10 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-NrtyoxlDnTZA1zExntD:-Nrtyoxm7HtkL87Lg1EC:b-yr295e) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e3eb5b54d225f681ec0b87a44d4f686758417ebd/backend/Pipfile#L10)):*
> ```TOML
> #   https://github.com/ocadotechnology/codeforlife-package-python/blob/{ref}/Pipfile
> # Replace "{ref}" in the above URL with the ref set below.
> codeforlife = {ref = "bulk_transfer_students", git = "https://github.com/ocadotechnology/codeforlife-package-python.git"}
> ```

Update


<!-- Sent from Reviewable.io -->

2024-03-07 10:06 UTC, SKairinos reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311)* status: 3 of 17 files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[`backend/Pipfile` line 10 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-NrtyoxlDnTZA1zExntD:-NsNN7go0D9VZQvd7eoe:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e3eb5b54d225f681ec0b87a44d4f686758417ebd/backend/Pipfile#L10)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Update
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-07 10:38 UTC, faucomte97 requested changes
> Reviewed 5 of 16 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311)* status: all files reviewed, 6 unresolved discussions (waiting on @SKairinos)

___
*[`backend/api/serializers/user.py` line 245 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-NsNU-S47OOx3slc18NP:-NsNU-S47OOx3slc18NQ:bme6ha0) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/922e37912a1deb5c35fafb9bd61105b70464cd2f/backend/api/serializers/user.py#L245)):*
> ```Python
>     def update(self, instance, validated_data):
>         for student_user, data in zip(instance, validated_data):
>             student_user.student.class_field = Class.objects.get(
> ```

Does the queryset already check whether the Class that's retrieved here is in the same school as the requester?
___
*[`backend/api/serializers/user.py` line 246 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-NsNU7ytEQBEfl8se6w8:-NsNU7ytEQBEfl8se6w9:b-fh731) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/922e37912a1deb5c35fafb9bd61105b70464cd2f/backend/api/serializers/user.py#L246)):*
> ```Python
>         for student_user, data in zip(instance, validated_data):
>             student_user.student.class_field = Class.objects.get(
>                 access_code=data["new_student"]["class_field"]["access_code"]
> ```

In theory the requester here could submit a request and assign different destination classes to different students in the same request, correct? If so, we don't currently support that so maybe we should enforce a check that the request sends all students to the same class?
___
*[`backend/api/serializers/user.py` line 248 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-NsNRO8m1dCJ9qGOAVSg:-NsNRO8m1dCJ9qGOAVSh:bcq5s9c) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/922e37912a1deb5c35fafb9bd61105b70464cd2f/backend/api/serializers/user.py#L248)):*
> ```Python
>                 access_code=data["new_student"]["class_field"]["access_code"]
>             )
>             student_user.student.save(update_fields=["class_field"])
> ```

You're missing a step in the flow.

First, the teacher selects the students they want to transfer to a new class.
Second, the teacher has to double-check the names are all unique.

![screencapture-localhost-8000-teach-class-XMNPF-students-move-disambiguate-2024-03-07-10\_32\_45.png](https://files.reviewableusercontent.io/images/reviewable/33633200/FF6hxiZWIAIXmW5QrX0fbnsu/screencapture-localhost-8000-teach-class-XMNPF-students-move-disambiguate-2024-03-07-10_32_45.png)

During this step the teacher can edit the names of his students to ensure they don't clash with the names in the destination class.
___
*[`backend/api/tests/serializers/test_user.py` line 106 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-NsNRjjM7t6okPVlMfuP:-NsNRjjM7t6okPVlMfuQ:b-uiymj) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/922e37912a1deb5c35fafb9bd61105b70464cd2f/backend/api/tests/serializers/test_user.py#L106)):*
> ```Python
>         self.class_2 = Class.objects.get(name="Class 2 @ School 1")
> 
>         # TODO: make this a property of Class in new data schema.
> ```

Wouldn't this just be the same as calling the `related_name` of the `class_field` on the `Student` model, ie `students`?
___
*[`backend/api/tests/views/test_user.py` line 146 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-NsNQIpB4avF2ysFvldp:-NsNQIpB4avF2ysFvldq:b-je8edz) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/a6a0d7772959e95ac9e69ee5aa5c83cd795088df/backend/api/tests/views/test_user.py#L146)):*
> ```Python
>         )
> 
>     def test_get_queryset__bulk__delete(self):
> ```

Why delete this?
___
*[`backend/api/views/user.py` line 35 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-NsNQYk7983mbJeIPl1z:-NsNQYk7983mbJeIPl2-:b-2vougt) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/922e37912a1deb5c35fafb9bd61105b70464cd2f/backend/api/views/user.py#L35)):*
> ```Python
> # pylint: disable-next=missing-class-docstring,too-many-ancestors
> class UserViewSet(_UserViewSet):
>     http_method_names = ["get", "post", "patch", "delete", "put"]
> ```

Why are we using put and not patch?


<!-- Sent from Reviewable.io -->

2024-03-13 10:12 UTC, SKairinos commented
*[`backend/api/serializers/user.py` line 248 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-NsNRO8m1dCJ9qGOAVSg:-NsrIC3EANalGSQec_ai:bb6un1j) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/922e37912a1deb5c35fafb9bd61105b70464cd2f/backend/api/serializers/user.py#L248)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

You're missing a step in the flow.

First, the teacher selects the students they want to transfer to a new class.
Second, the teacher has to double-check the names are all unique.

![screencapture-localhost-8000-teach-class-XMNPF-students-move-disambiguate-2024-03-07-10\_32\_45.png](https://files.reviewableusercontent.io/images/reviewable/33633200/FF6hxiZWIAIXmW5QrX0fbnsu/screencapture-localhost-8000-teach-class-XMNPF-students-move-disambiguate-2024-03-07-10_32_45.png)

During this step the teacher can edit the names of his students to ensure they don't clash with the names in the destination class.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-03-13 10:19 UTC, SKairinos reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311)* status: 5 of 24 files reviewed, 7 unresolved discussions (waiting on @faucomte97)

___
*[`backend/api/tests/serializers/test_user.py` line 106 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-NsNRjjM7t6okPVlMfuP:-NsrIKGcCk1aMtZ4PgqY:b-132xnq) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/922e37912a1deb5c35fafb9bd61105b70464cd2f/backend/api/tests/serializers/test_user.py#L106)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Wouldn't this just be the same as calling the `related_name` of the `class_field` on the `Student` model, ie `students`?
</blockquote></details>

no longer relevant
___
*[`backend/api/tests/views/test_user.py` line 146 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-NsNQIpB4avF2ysFvldp:-NsrIlDD95YFK2VgVFWR:bxsrxm6) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/a6a0d7772959e95ac9e69ee5aa5c83cd795088df/backend/api/tests/views/test_user.py#L146)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Why delete this?
</blockquote></details>

no longer relevant. these test exist on the student view set
___
*[`backend/api/views/user.py` line 35 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-NsNQYk7983mbJeIPl1z:-NsrIuKa63b5hFU09sj1:b-1e8wv5) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/922e37912a1deb5c35fafb9bd61105b70464cd2f/backend/api/views/user.py#L35)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Why are we using put and not patch?
</blockquote></details>

We are using put because all **custom** actions use put, not patch. Patch is for partially updating a model (forces all required serializer fields to be optional). Put is for providing all data necessary to complete an action (required fields stay required). For example, when transferring a student from one class to another, the klass field is required. This should not be PATCHed, it should be PUTed. 😂


<!-- Sent from Reviewable.io -->

2024-03-13 13:14 UTC, faucomte97 requested changes
> Reviewed 19 of 19 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311)* status: all files reviewed, 18 unresolved discussions (waiting on @SKairinos)

___
*[`backend/api/serializers/student.py` line 55 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-NsnQY0ID1ZBPuXPv3_Z:-NsrPhvcDJKzc-j4OT9Y:bbsl1cq) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3b8618c32d6fc8216ed64a283beb65eaec70a984/backend/api/serializers/student.py#L55)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

make case insensitive with first_name.lower()
</blockquote></details>

Yes :thumbsup: 
___
*[`backend/api/serializers/student.py` line 204 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-NsrTFf13jF7NnxrAC_U:-NsrTFf2651SjZ6A0U7s:bhta48m) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3b8618c32d6fc8216ed64a283beb65eaec70a984/backend/api/serializers/student.py#L204)):*
> ```Python
> 
>             user_fields = t.cast(DataDict, data["new_user"])
>             student.new_user.email = user_fields["email"]
> ```

Just realised that the `username` field needs to be set to the email value too.
Update tests too if needed
___
*[`backend/api/serializers/student.py` line 222 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-NsrTuLvC58hVxMGezZj:-NsrTuLvC58hVxMGezZk:bieaj9a) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3b8618c32d6fc8216ed64a283beb65eaec70a984/backend/api/serializers/student.py#L222)):*
> ```Python
>                 **BaseUserSerializer.Meta.extra_kwargs,
>                 "first_name": {"required": False},
>                 "email": {"read_only": False},
> ```

Might need to add `username` in here as not read only
___
*[`backend/api/serializers/student.py` line 235 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-NsrU6kO5HYyy02cfG1K:-NsrU6kO5HYyy02cfG1L:bxmqgx2) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3b8618c32d6fc8216ed64a283beb65eaec70a984/backend/api/serializers/student.py#L235)):*
> ```Python
>     def update(self, instance, validated_data):
>         for student, data in zip(instance, validated_data):
>             student.class_field = Class.objects.get(
> ```

If this is to allow different students to be transferred to different classes in one call then fair enough, but I just thought that we could get the class the students are being moved to before the loop so we don't perform x `get`s where x is the number of students the teacher is moving.
___
*[`backend/api/serializers/user.py` line 143 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-NsrWYjf4UEQK5sWeZY7:-NsrWYjf4UEQK5sWeZY8:bm0m97d) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3b8618c32d6fc8216ed64a283beb65eaec70a984/backend/api/serializers/user.py#L143)):*
> ```Python
>                         "Teacher can't request to join a class.",
>                         code="requesting_to_join_class__teacher__update",
>                     )
> ```

Didn't you say you had removed this check since a Teacher can't have the `new_student` attr anyway?
The check here should just be `if "new_student" in attrs`, right?



_Code quote:_
```Python
            if self.instance.teacher:
                if (
                    "new_student" in attrs
                    and "pending_class_request" in attrs["new_student"]
                ):
                    raise serializers.ValidationError(
                        "Teacher can't request to join a class.",
                        code="requesting_to_join_class__teacher__update",
                    )
```
___
*[`backend/api/serializers/user.py` line 145 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-NsrWrQe07H5BEfP16at:-NsrWrQe07H5BEfP16au:buv4h3t) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3b8618c32d6fc8216ed64a283beb65eaec70a984/backend/api/serializers/user.py#L145)):*
> ```Python
>                     )
> 
>             elif self.instance.student:
> ```

Side note: Should we add a check in here, similar to above, to ensure a student instance cannot be updated with a `new_teacher` attribute?
___
*[`backend/api/tests/serializers/test_student.py` line 43 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-NsrYSDf4J7dHTleZDlX:-NsrYSDf4J7dHTleZDlY:bdqjns6) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3b8618c32d6fc8216ed64a283beb65eaec70a984/backend/api/tests/serializers/test_student.py#L43)):*
> ```Python
> 
>     def setUp(self):
>         student_user = StudentUser.objects.first()
> ```

This just gets Leonardo doesn't it? Ie, nothing to do with the `school_1` fixture, right?
___
*[`backend/api/tests/serializers/test_student.py` line 81 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-NsrZ0NC9SIMsSWb3oPc:-NsrZ0NC9SIMsSWb3oPd:bk7czl8) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3b8618c32d6fc8216ed64a283beb65eaec70a984/backend/api/tests/serializers/test_student.py#L81)):*
> ```Python
>     def test_validate__first_name__db__exists_in_class(self):
>         """
>         Cannot provide transfer a student to another class if their first name
> ```

remove "provide"
___
*[`backend/api/tests/serializers/test_student.py` line 129 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-NsrZadaEJ3Umf4g8Zzu:-NsrZadaEJ3Umf4g8Zzv:b-ruoax7) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3b8618c32d6fc8216ed64a283beb65eaec70a984/backend/api/tests/serializers/test_student.py#L129)):*
> ```Python
>         klass = Class.objects.exclude(
>             teacher__school=user.teacher.school
>         ).first()
> ```

This will get Albert Einstein, correct? Ie, not data from the fixtures.
___
*[`backend/api/tests/serializers/test_student.py` line 166 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-NsrZsVP77iWZhtgh94_:-NsrZsVP77iWZhtgh94a:bdqjns6) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3b8618c32d6fc8216ed64a283beb65eaec70a984/backend/api/tests/serializers/test_student.py#L166)):*
> ```Python
> 
>     def setUp(self):
>         student = Student.objects.first()
> ```

This just gets Leonardo doesn't it? Ie, nothing to do with the `school_1` fixture, right?
___
*[`backend/api/tests/serializers/test_student.py` line 192 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-NsrZzCe83MBtis80pPX:-NsrZzCe83MBtis80pPY:bfp7rpf) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3b8618c32d6fc8216ed64a283beb65eaec70a984/backend/api/tests/serializers/test_student.py#L192)):*
> ```Python
> 
>     def setUp(self):
>         klass = Class.objects.first()
> ```

This just gets Class AB123 doesn't it? Ie, nothing to do with the `school_1` fixture, right?
___
*[`backend/api/tests/serializers/test_student.py` line 217 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-Nsr_qbDDFr4vlJ0j4cn:-Nsr_qbDDFr4vlJ0j4co:bdqjns6) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3b8618c32d6fc8216ed64a283beb65eaec70a984/backend/api/tests/serializers/test_student.py#L217)):*
> ```Python
> 
>     def setUp(self):
>         student = Student.objects.first()
> ```

This just gets Leonardo doesn't it? Ie, nothing to do with the `school_1` fixture, right?
___
*[`backend/api/tests/serializers/test_student.py` line 233 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-NsraKVlE4wubqnTgk2l:-NsraKVlE4wubqnTgk2m:byov5vh) ([raw file](htt [...]

2024-03-14 16:24 UTC, SKairinos reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311)* status: 18 of 25 files reviewed, 18 unresolved discussions (waiting on @faucomte97)

___
*[`backend/api/serializers/student.py` line 55 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-NsnQY0ID1ZBPuXPv3_Z:-NssBEbm9DNJPb1efwKO:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3b8618c32d6fc8216ed64a283beb65eaec70a984/backend/api/serializers/student.py#L55)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Yes :thumbsup:
</blockquote></details>

Done.
___
*[`backend/api/serializers/student.py` line 204 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-NsrTFf13jF7NnxrAC_U:-NssBa_pCAK0-2zy9i0Z:bdhsogm) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3b8618c32d6fc8216ed64a283beb65eaec70a984/backend/api/serializers/student.py#L204)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Just realised that the `username` field needs to be set to the email value too.
Update tests too if needed
</blockquote></details>

we have [a signal](https://github.com/ocadotechnology/codeforlife-portal-react/blob/93dd89ce9a4f022d28c65d0574b270419e7a581d/backend/api/signals/user.py#L30) that handles this
___
*[`backend/api/serializers/student.py` line 222 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-NsrTuLvC58hVxMGezZj:-NssBytPD3umfxO7_khW:b-8m3ct7) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3b8618c32d6fc8216ed64a283beb65eaec70a984/backend/api/serializers/student.py#L222)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Might need to add `username` in here as not read only
</blockquote></details>

username is not a field a user-field in the new schema so it's intentionally omitted from the data-access layer
___
*[`backend/api/serializers/student.py` line 235 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-NsrU6kO5HYyy02cfG1K:-NssCIkFEuTUWQ9Fpny0:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3b8618c32d6fc8216ed64a283beb65eaec70a984/backend/api/serializers/student.py#L235)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

If this is to allow different students to be transferred to different classes in one call then fair enough, but I just thought that we could get the class the students are being moved to before the loop so we don't perform x `get`s where x is the number of students the teacher is moving.
</blockquote></details>

Done.
___
*[`backend/api/serializers/user.py` line 143 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-NsrWYjf4UEQK5sWeZY7:-NssLe3OE1HQkuhoM8BS:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3b8618c32d6fc8216ed64a283beb65eaec70a984/backend/api/serializers/user.py#L143)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Didn't you say you had removed this check since a Teacher can't have the `new_student` attr anyway?
The check here should just be `if "new_student" in attrs`, right?
</blockquote></details>

Done.
___
*[`backend/api/serializers/user.py` line 145 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-NsrWrQe07H5BEfP16at:-NssMwrpA34ey5XhR5Pt:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3b8618c32d6fc8216ed64a283beb65eaec70a984/backend/api/serializers/user.py#L145)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Side note: Should we add a check in here, similar to above, to ensure a student instance cannot be updated with a `new_teacher` attribute?
</blockquote></details>

Done.
___
*[`backend/api/tests/serializers/test_student.py` line 43 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-NsrYSDf4J7dHTleZDlX:-NssNM8n6QsdLPpZZj60:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3b8618c32d6fc8216ed64a283beb65eaec70a984/backend/api/tests/serializers/test_student.py#L43)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

This just gets Leonardo doesn't it? Ie, nothing to do with the `school_1` fixture, right?
</blockquote></details>

Done.
___
*[`backend/api/tests/serializers/test_student.py` line 81 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-NsrZ0NC9SIMsSWb3oPc:-NssNPnj-ot4-mURuMrV:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3b8618c32d6fc8216ed64a283beb65eaec70a984/backend/api/tests/serializers/test_student.py#L81)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

remove "provide"
</blockquote></details>

Done.
___
*[`backend/api/tests/serializers/test_student.py` line 129 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-NsrZadaEJ3Umf4g8Zzu:-NssNXDn9ZMOsgyWd3jy:b-nrtvkw) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3b8618c32d6fc8216ed64a283beb65eaec70a984/backend/api/tests/serializers/test_student.py#L129)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

This will get Albert Einstein, correct? Ie, not data from the fixtures.
</blockquote></details>

Done. Yes.
___
*[`backend/api/tests/serializers/test_student.py` line 166 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-NsrZsVP77iWZhtgh94_:-NssNnPO1EmIgA_oCufo:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3b8618c32d6fc8216ed64a283beb65eaec70a984/backend/api/tests/serializers/test_student.py#L166)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

This just gets Leonardo doesn't it? Ie, nothing to do with the `school_1` fixture, right?
</blockquote></details>

Done.
___
*[`backend/api/tests/serializers/test_student.py` line 192 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-NsrZzCe83MBtis80pPX:-NssNog5684XnxJK6-6i:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3b8618c32d6fc8216ed64a283beb65eaec70a984/backend/api/tests/serializers/test_student.py#L192)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

This just gets Class AB123 doesn't it? Ie, nothing to do with the `school_1` fixture, right?
</blockquote></details>

Done.
___
*[`backend/api/tests/serializers/test_student.py` line 217 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-Nsr_qbDDFr4vlJ0j4cn:-NssNwIs5Be7i51VnZK9:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3b8618c32d6fc8216ed64a283beb65eaec70a984/backend/api/tests/serializers/test_student.py#L217)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

This just gets Leonardo doesn't it? Ie, nothing to do with the `school_1` fixture, right?
</blockquote></details>

Done.
___
*[`backend/api/tests/serializers/test_student.py` line 233 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-NsraKVlE4wubqnTgk2l:-NssNxAT0mL01RyIkD0S:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3b8618c32d6fc8216ed64a283beb65eaec70a984/backend/api/tests/serializers/test_student.py#L233)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Username too (set to email)
</blockquote [...]

2024-03-14 16:32 UTC, faucomte97 requested changes
> Reviewed 7 of 7 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311)* status: all files reviewed, 2 unresolved discussions (waiting on @SKairinos)

___
*[`backend/api/tests/serializers/test_student.py` line 108 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-Nsxme_05Sitb6JEBNFU:-Nsxme_05Sitb6JEBNFV:b-7h9nfu) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3b8618c32d6fc8216ed64a283beb65eaec70a984/backend/api/tests/serializers/test_student.py#L108)):*
> ```Python
>         )
> 
>     def test_validate_klass__does_not_exist(self):
> ```

what?
___
*[`backend/api/tests/serializers/test_student.py` line 283 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-Nsrb3Jp0u4ToDDB9CwG:-NsxmrvyCKICwPVe4zN5:bkvzcd6) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3b8618c32d6fc8216ed64a283beb65eaec70a984/backend/api/tests/serializers/test_student.py#L283)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

can't see no change


<!-- Sent from Reviewable.io -->

2024-03-14 16:51 UTC, SKairinos reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311)* status: 24 of 25 files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[`backend/api/tests/serializers/test_student.py` line 108 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-Nsxme_05Sitb6JEBNFU:-NsxofjF3H8EQOdtHRX8:bl0pa3k) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3b8618c32d6fc8216ed64a283beb65eaec70a984/backend/api/tests/serializers/test_student.py#L108)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

what?
</blockquote></details>

my bad. the def should not have been deleted. The tests were still running as the test's func body was just being inside the setUp() instead (the above def). Since the test passes, it didn't cause an issue inside of setUp()
___
*[`backend/api/tests/serializers/test_student.py` line 283 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-Nsrb3Jp0u4ToDDB9CwG:-NsxruTOAawlYYfdPy2_:bo0vwbm) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3b8618c32d6fc8216ed64a283beb65eaec70a984/backend/api/tests/serializers/test_student.py#L283)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

can't see no change
</blockquote></details>

Double Done.


<!-- Sent from Reviewable.io -->

2024-03-14 16:53 UTC, faucomte97 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/311#-:-NsxsXX--oRaDYay34b7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)



<!-- Sent from Reviewable.io -->

2024-03-14 16:53 UTC, merged