2093 fix remaining components
ocadotechnology/codeforlife-portal-react pull request #48
Opened 2023-06-26 11:24 UTC by SKairinos

2023-06-26 16:06 UTC, SKairinos reviewed
> Reviewed 2 of 16 files at r1, 8 of 13 files at r2, 10 of 34 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48)* status: 19 of 50 files reviewed, 11 unresolved discussions

___
*[`frontend/src/app/router.tsx` line 65 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYs4f8V8K54erssMGr0:-NYs4f8V8K54erssMGr1:b-k22twu) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/07657e1d0e26ccd09b862e106e67c2707384dd6a/frontend/src/app/router.tsx#L65)):*
> ```XML
>       }),
>       independent: _('/?userType=independent', {
>         account: _('?view=account'),
> ```

this should start with "&", not "?"
___
*[`frontend/src/app/router.tsx` line 84 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYs5RBjBpLmtQkJcuH6:-NYs5RBjBpLmtQkJcuH7:bt127ug) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/07657e1d0e26ccd09b862e106e67c2707384dd6a/frontend/src/app/router.tsx#L84)):*
> ```XML
>   termsOfUse: _('/terms-of-use'),
>   newsletter: _('/newsletter'),
>   dotmailerConsent: _('/dotmailer-consent'),
> ```

let's rename this url and component to '/communication-preferences'
___
*[`frontend/src/pages/dotmailerConsent/DotmailerConsent.tsx` line 33 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYs8lR43vDjLdfLW01w:-NYs8lR43vDjLdfLW01x:bhef24p) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/07657e1d0e26ccd09b862e106e67c2707384dd6a/frontend/src/pages/dotmailerConsent/DotmailerConsent.tsx#L33)):*
> ```XML
>             placeholder="Email address"
>             helperText="Enter your email address"
>             sx={{ width: '60%' }}
> ```

don't restrict the width like this. it's not centred and notice how bad this looks on mobile because it's 60% of a small screen. Rather, restrict the max width of the page section. For example, "<Page.Section maxWidth='md' ...". FYI, the [maxWidth for all Containers is 'lg' by default](https://github.com/ocadotechnology/codeforlife-package-javascript/blob/8dc908c9c05be61bf0b0d222d91f966a45d89c28/src/theme/components/MuiContainer.ts#L5C14-L5C14).
___
*[`frontend/src/pages/studentsDashboard/BaseDashboard.tsx` line 49 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYsFb50ED3dPrzm5RGq:-NYsFb514U4wFvrl47Sz:b-omkyxo) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/07657e1d0e26ccd09b862e106e67c2707384dd6a/frontend/src/pages/studentsDashboard/BaseDashboard.tsx#L49)):*
> ```XML
>       break;
>     case 'join':
>       pageView = <JoinSchool goBack={() => { setView(undefined); }}/>;
> ```

need to check if the user isDependent. This link should raise an error:
http://localhost:3000/student/dashboard/?userType=dependent&view=join
___
*[`frontend/src/pages/studentsDashboard/account/StudentAccount.tsx` line 12 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYsGx4J1NVoJhBBE9oY:-NYsGx4J1NVoJhBBE9oZ:b-dfet23) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/07657e1d0e26ccd09b862e106e67c2707384dd6a/frontend/src/pages/studentsDashboard/account/StudentAccount.tsx#L12)):*
> ```XML
> 
> const AccountFormPasswordFields: React.FC = () => {
>   return <>
> ```

Wrap these fields in a stack with direction='row'. change direction to column on smaller screens.
___
*[`frontend/src/pages/studentsDashboard/account/StudentAccount.tsx` line 14 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYsHxQG2274beUOHhXs:-NYsHxQG2274beUOHhXt:b8pwuo4) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/07657e1d0e26ccd09b862e106e67c2707384dd6a/frontend/src/pages/studentsDashboard/account/StudentAccount.tsx#L14)):*
> ```XML
>   return <>
>     <Grid item sm={4}>
>       <TextField
> ```

import PasswordField from CFL package and remove the endAdornment. it is [set by default](https://github.com/ocadotechnology/codeforlife-package-javascript/blob/93a48a0f45bc9882900bb642a1218f32a549caea/src/components/form/PasswordField.tsx#L31C10-L31C10). Also, I updated the CFL package so password fields are optional by default (used to always be required).
___
*[`frontend/src/pages/studentsDashboard/account/StudentAccount.tsx` line 29 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYsHqgP8WeNX6QLuc6s:-NYsHqgP8WeNX6QLuc6t:b-lbt6a2) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/07657e1d0e26ccd09b862e106e67c2707384dd6a/frontend/src/pages/studentsDashboard/account/StudentAccount.tsx#L29)):*
> ```XML
>     </Grid>
>     <Grid item sm={4}>
>       <TextField
> ```

use the repeat={[]} prop on the above password field
___
*[`frontend/src/pages/studentsDashboard/account/StudentAccount.tsx` line 37 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYsOaSd8Sb666REI0Lw:-NYsOaSd8Sb666REI0Lx:b-nwoezx) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/07657e1d0e26ccd09b862e106e67c2707384dd6a/frontend/src/pages/studentsDashboard/account/StudentAccount.tsx#L37)):*
> ```XML
>     </Grid>
>     <Grid item sm={4}>
>       <TextField
> ```

use password field and set endAdornment since it defers from the default 
___
*[`frontend/src/pages/studentsDashboard/account/StudentAccount.tsx` line 146 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYsPUlv9bhLdnur_O7P:-NYsPUlv9bhLdnur_O7Q:b-p9tsve) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/07657e1d0e26ccd09b862e106e67c2707384dd6a/frontend/src/pages/studentsDashboard/account/StudentAccount.tsx#L146)):*
> ```XML
>           </Grid>
>           <Grid item sm={6}>
>             <TextField
> ```

use email field and remove endAdornment
___
*[`frontend/src/pages/studentsDashboard/joinSchool/JoinSchool.tsx` line 19 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYsQlq89GfLrStzEqp2:-NYsQlq89GfLrStzEqp3:b-aw4c7u) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/07657e1d0e26ccd09b862e106e67c2707384dd6a/frontend/src/pages/studentsDashboard/joinSchool/JoinSchool.tsx#L19)):*
> ```XML
>   };
> 
>   const [requestSent, setRequestSent] = React.useState<boolean>(false);
> ```

no need to specify type <boolean>. it is inferred from the false.
___
*[`frontend/src/pages/studentsDashboard/joinSchool/JoinSchool.tsx` line 66 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYsRCxDDl5QOSmBk_-x:-NYsRCxDDl5QOSmBk_-y:b-kadqzn) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/07657e1d0e26ccd09b862e106e67c2707384dd6a/frontend/src/pages/studentsDashboard/joinSchool/JoinSchool.tsx#L66)):*
> ```XML
>             }}
>           >
>             <Grid container spacing={2}>
> ```

A simpler approach to this is "<TextField sx={{ width: { xs: '100%', sm: '50%' } }} ..."


<!-- Sent from Reviewable.io -->

2023-06-27 11:30 UTC, faucomte97 requested changes
> Reviewed 1 of 16 files at r1, 21 of 34 files at r3, 1 of 1 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48)* status: 45 of 52 files reviewed, 32 unresolved discussions (waiting on @SKairinos)

*[a discussion](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYwZ3Xc2xyMxVechVI3:-NYwZ3Xc2xyMxVechVI4:b-s0xo57) (no related file):*
I've noticed that the breakpoints don't match the ones we currently have (especially the mobile / tablet cutoff) - might need to check with Laura to see what she things

___
___
*[`.github/workflows/main.yml` line 70 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYwCZ2V-0beSOpmeUTt:-NYwCZ2V-0beSOpmeUTu:b-615vr3) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/010255df0dada57102e22901238acbe985e2358d/.github/workflows/main.yml#L70)):*
> ```YAML
>       - name: 🛫 Checkout
>         uses: actions/checkout@v3
>       
> ```

Extra whitespaces
___
*[`.github/workflows/main.yml` line 121 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYwD1lJA1FaYfp53boG:-NYwD1lJA1FaYfp53boH:braf3ml) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/010255df0dada57102e22901238acbe985e2358d/.github/workflows/main.yml#L121)):*
> ```YAML
>         working-directory: ./backend
>         run: pipenv requirements > requirements.txt
> ```

Just had a thought - we don't have a step here to run the migrations.
We can probably add it in later but still thought I'd point it out.
___
*[`.github/workflows/main.yml` line 124 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYwCly-3mrbBfnv9vVF:-NYwCly-3mrbBfnv9vVG:b-615vr3) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/010255df0dada57102e22901238acbe985e2358d/.github/workflows/main.yml#L124)):*
> ```YAML
>       - name: 🛠 Collect Static Files
>         working-directory: ./backend
>         run: pipenv run python ./manage.py collectstatic --noinput --clear        
> ```

Extra whitespaces
___
*[`backend/Pipfile` line 8 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYwDFAo-IOnKamLEshg:-NYwDFAo-IOnKamLEshh:b-6qklbv) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/010255df0dada57102e22901238acbe985e2358d/backend/Pipfile#L8)):*
> ```TOML
> [packages]
> codeforlife = {ref = "v0.1.12", git = "https://github.com/ocadotechnology/codeforlife-package-python.git"}
> whitenoise = "==6.5.0"
> ```

Maybe have a quick look into why we don't need this in the current aimmo setup and if we can do the same here
___
*[`backend/service/settings.py` line 27 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYwDTvuBs3w3UXFQJ5z:-NYwDTvuBs3w3UXFQJ6-:bolfm0q) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/010255df0dada57102e22901238acbe985e2358d/backend/service/settings.py#L27)):*
> ```Python
> 
> # SECURITY WARNING: don't run with debug turned on in production!
> DEBUG = bool(int(os.getenv("DEBUG", "1")))
> ```

Should we just use True or False instead of numbers so we at least can skip the casting to int step?
___
*[`frontend/src/features/header/Header.tsx` line 24 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYwbHdY6-7Q03waHwab:-NYwbHdY6-7Q03waHwac:b8pi5ck) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/010255df0dada57102e22901238acbe985e2358d/frontend/src/features/header/Header.tsx#L24)):*
> ```XML
> } from './user';
> 
> const Header: React.FC = () => {
> ```

Wherever you hover over the header, the mouse pointer is the click icon. Slightly confusing because it makes it seem clickable - probably a side effect of it being an Accordion kind of? Would be nice to disable it.
___
*[`frontend/src/features/header/Header.tsx` line 85 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYwEcPg54K6RFvwU9CQ:-NYwEcPg54K6RFvwU9CR:bvsw2z0) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/010255df0dada57102e22901238acbe985e2358d/frontend/src/features/header/Header.tsx#L85)):*
> ```XML
>           padding: '0px !important',
>           [`.${buttonClasses.root}`]: {
>             padding: '24px 12px',
> ```

Magic padding numbers? :thinking: 
Should we be using either a) predefined padding values from the JS package or b) flexbox?

second thought as I write this: this is specifically for the mobile accordion right? In that case, I understand this more because it's a more rogue component. Maybe it's fine to leave it as it is.
___
*[`frontend/src/features/header/details/DetailsAccordion.tsx` line 50 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYwG8tbC7bFTgjyQ9u4:-NYwG8tbC7bFTgjyQ9u5:b-7ixgu7) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/010255df0dada57102e22901238acbe985e2358d/frontend/src/features/header/details/DetailsAccordion.tsx#L50)):*
> ```XML
>     >
>       <AccordionSummary
>         expandIcon={<ExpandMoreIcon />}
> ```

If I'm correct in thinking that this is the nested Accordion component (eg, the Log In accordion), then this icon doesn't match what we currently have on the website, it should be a full arrow.
___
*[`frontend/src/features/header/user/Authenticated.tsx` line 55 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYwZvp6CBuWx8U4wAKl:-NYwZvp6CBuWx8U4wAKm:b-r8vmow) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/010255df0dada57102e22901238acbe985e2358d/frontend/src/features/header/user/Authenticated.tsx#L55)):*
> ```XML
>     {children}
>     <SummaryLoginSelect
>       width='220px'
> ```

Fixed width instead of dynamic?
___
*[`frontend/src/features/header/user/Independent.tsx` line 37 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYw_DJnDBjwXc7B7wJd:-NYw_DJnDBjwXc7B7wJe:b7lb7ds) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/010255df0dada57102e22901238acbe985e2358d/frontend/src/features/header/user/Independent.tsx#L37)):*
> ```XML
>       menuItemsProps={[
>         {
>           children: 'Update account details',
> ```

Link to independent account details page please
___
*[`frontend/src/features/header/user/Independent.tsx` line 75 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYwaoLj0XhveMohwgwd:-NYwaoLj0XhveMohwgwe:b-6o8fqu) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/010255df0dada57102e22901238acbe985e2358d/frontend/src/features/header/user/Independent.tsx#L75)):*
> ```XML
> 
>   return (
>     <AuthenticatedDetails>
> ```

We don't have the option to reset password in this menu, this might be an existing flaw on the current website
___
*[`frontend/src/features/header/user/Independent.tsx` line 79 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYw_RzH53DLhu-96SPk:-NYw_RzH53DLhu-96SPl:bbwkk6h) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/010255df0dada57102e22901238acbe985e2358d/frontend/src/features/header/user/Independent.tsx#L79)):*
> ```XML
>         <DetailsButton
>           spacing={2}
>           href={paths.student.dashboard.dependent._}
> ```

Independent, not dependent
___
*[`frontend/src/features/header/user/Student.tsx` line 30 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYw_qPF5qeOqFfgJ64o:-NYw_qPF5qeOqFfgJ64p:bwkfh41) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/010255df0dada57102e22901238acbe985e2358d/frontend/src/features/header/user/Student.tsx#L30)):*
> ```XML
>       menuItemsProps={[
>         {
>           children: 'Change password',
> ```

Link to stu [...]

2023-06-27 15:48 UTC, SKairinos reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48)* status: 39 of 52 files reviewed, 32 unresolved discussions (waiting on @faucomte97)

___
*[`.github/workflows/main.yml` line 70 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYwCZ2V-0beSOpmeUTt:-NYwrp9r49X3-qBxxjq_:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/010255df0dada57102e22901238acbe985e2358d/.github/workflows/main.yml#L70)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Extra whitespaces
</blockquote></details>

Done.
___
*[`.github/workflows/main.yml` line 121 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYwD1lJA1FaYfp53boG:-NYwsZTSE7IwugFdi4pg:bzgvtks) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/010255df0dada57102e22901238acbe985e2358d/.github/workflows/main.yml#L121)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Just had a thought - we don't have a step here to run the migrations.
We can probably add it in later but still thought I'd point it out.
</blockquote></details>

Not a fan of running migrations in the pipeline because it doesn't always go off without a hitch. However, I have added a step to check if there are any pending migrations. If so, it'll error out.
___
*[`.github/workflows/main.yml` line 124 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYwCly-3mrbBfnv9vVF:-NYwsvMG2GpqbaPDTBeW:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/010255df0dada57102e22901238acbe985e2358d/.github/workflows/main.yml#L124)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Extra whitespaces
</blockquote></details>

Done.
___
*[`backend/service/settings.py` line 27 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYwDTvuBs3w3UXFQJ5z:-NYwtsYO-M4LxZXBYwnQ:b-f1tuej) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/010255df0dada57102e22901238acbe985e2358d/backend/service/settings.py#L27)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Should we just use True or False instead of numbers so we at least can skip the casting to int step?
</blockquote></details>

an int can be natively cast to a bool. string:"False" will not equal bool:False because all bool does with strings is look at their length. If the string length == 0, then it's False. If > 0, the then bool is True. So "False" will equal True.
___
*[`frontend/src/features/header/Header.tsx` line 24 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYwbHdY6-7Q03waHwab:-NYwvG1E66IF_nacHLlW:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/010255df0dada57102e22901238acbe985e2358d/frontend/src/features/header/Header.tsx#L24)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Wherever you hover over the header, the mouse pointer is the click icon. Slightly confusing because it makes it seem clickable - probably a side effect of it being an Accordion kind of? Would be nice to disable it.
</blockquote></details>

Done.
___
*[`frontend/src/features/header/Header.tsx` line 85 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYwEcPg54K6RFvwU9CQ:-NYwvYK26790UBsCTMy4:b4afixk) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/010255df0dada57102e22901238acbe985e2358d/frontend/src/features/header/Header.tsx#L85)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Magic padding numbers? :thinking: 
Should we be using either a) predefined padding values from the JS package or b) flexbox?

second thought as I write this: this is specifically for the mobile accordion right? In that case, I understand this more because it's a more rogue component. Maybe it's fine to leave it as it is.
</blockquote></details>

Yes, some magic padding 
___
*[`frontend/src/features/header/details/DetailsAccordion.tsx` line 50 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYwG8tbC7bFTgjyQ9u4:-NYwxGS63NJysTqIr8kw:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/010255df0dada57102e22901238acbe985e2358d/frontend/src/features/header/details/DetailsAccordion.tsx#L50)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

If I'm correct in thinking that this is the nested Accordion component (eg, the Log In accordion), then this icon doesn't match what we currently have on the website, it should be a full arrow.
</blockquote></details>

Done.
___
*[`frontend/src/features/header/user/Authenticated.tsx` line 55 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYwZvp6CBuWx8U4wAKl:-NYwy9uN-8Oe1Kxw2iYG:b-jo43ww) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/010255df0dada57102e22901238acbe985e2358d/frontend/src/features/header/user/Authenticated.tsx#L55)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Fixed width instead of dynamic?
</blockquote></details>

I agree that there are better solutions than this but I took this approach due to time constraints. MUI has independent widths for select's summary and details by default so I had to hard code them to have the same width. In the future, I can create a custom component from scratch that has the desired behaviour. 
___
*[`frontend/src/features/header/user/Independent.tsx` line 37 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYw_DJnDBjwXc7B7wJd:-NYxLEBi7xwValkIhcry:b-7ysue8) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/010255df0dada57102e22901238acbe985e2358d/frontend/src/features/header/user/Independent.tsx#L37)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Link to independent account details page please
</blockquote></details>

Done. also did it for the student account.
___
*[`frontend/src/features/header/user/Independent.tsx` line 75 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYwaoLj0XhveMohwgwd:-NYxN4bvClz07RO_TARz:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/010255df0dada57102e22901238acbe985e2358d/frontend/src/features/header/user/Independent.tsx#L75)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

We don't have the option to reset password in this menu, this might be an existing flaw on the current website
</blockquote></details>

Done.
___
*[`frontend/src/features/header/user/Independent.tsx` line 79 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYw_RzH53DLhu-96SPk:-NYxM7YN09XQjNDrGiLJ:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/010255df0dada57102e22901238acbe985e2358d/frontend/src/features/header/user/Independent.tsx#L79)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Independent, not dependent
</blockquote></details>

Done.
___
*[`frontend/src/features/header/user/Student.tsx` line 30 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYw_qPF5qeOqFfgJ64o:-NYxLtr8A1a4LpX43feB:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/010255df0dada57102e22901238acbe985e2358d/frontend/src/features/header/user/Student.tsx#L30)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Link to student acco [...]

2023-06-27 16:39 UTC, SKairinos reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48)* status: 39 of 52 files reviewed, 32 unresolved discussions (waiting on @faucomte97)

___
*[`backend/Pipfile` line 8 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYwDFAo-IOnKamLEshg:-NYxXgEL-WuaGLQgU7fg:bvgdrxg) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/010255df0dada57102e22901238acbe985e2358d/backend/Pipfile#L8)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Maybe have a quick look into why we don't need this in the current aimmo setup and if we can do the same here
</blockquote></details>

handling this as part of the backend setup
___
*[`frontend/src/features/header/Header.tsx` line 85 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYwEcPg54K6RFvwU9CQ:-NYx_T1-CxP3hbO2rfiM:bf4v4b8) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/010255df0dada57102e22901238acbe985e2358d/frontend/src/features/header/Header.tsx#L85)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

Yes, some magic padding 
</blockquote></details>

didn't finish my previous comment. There is some magic padding, yes. And yes, this is specifically a mobile accordion. It's not the cleanest implementation but I'd like to add it as technical debt to come back and clean this up.
___
*[`frontend/src/features/header/user/Teacher.tsx` line 96 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYwaTMyD8YRGWgTD6cw:-NYxiMPd0SbUePraYAmB:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/010255df0dada57102e22901238acbe985e2358d/frontend/src/features/header/user/Teacher.tsx#L96)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Can be done now?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-27 18:00 UTC, faucomte97 requested changes
> Reviewed 1 of 16 files at r1, 9 of 34 files at r3, 5 of 6 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48)* status: 45 of 52 files reviewed, 15 unresolved discussions (waiting on @SKairinos)

___
*[`frontend/src/features/header/user/Teacher.tsx` line 93 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYwaML_483Fziqy-ooS:-NYy-PxjENcBZLzWdvWt:b-6ct4lq) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/010255df0dada57102e22901238acbe985e2358d/frontend/src/features/header/user/Teacher.tsx#L93)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

This is how it is on prod
</blockquote></details>

That's true but should we add it in?
___
*[`frontend/src/features/header/MenuAccordion.tsx` line 0 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYy-mco8ervLXJrZMFr:-NYy-mco8ervLXJrZMFs:b-y3aekc) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/dfdf7474a655f3bfe4b7632c1ede0088ae2fa76e/frontend/src/features/header/MenuAccordion.tsx#L0)):*
I don't understand, Reviewable says this file and the following ones have been deleted?


<!-- Sent from Reviewable.io -->

2023-06-27 18:33 UTC, faucomte97 reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48)* status: 45 of 52 files reviewed, 15 unresolved discussions (waiting on @SKairinos)

___
*[`frontend/src/app/router.tsx` line 65 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYs4f8V8K54erssMGr0:-NYy1CRa6hxQgAfuUANP:bx3iq6m) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/07657e1d0e26ccd09b862e106e67c2707384dd6a/frontend/src/app/router.tsx#L65)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

this should start with "&", not "?"
</blockquote></details>

Addressed
___
*[`frontend/src/app/router.tsx` line 84 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYs5RBjBpLmtQkJcuH6:-NYy1jnC-awsgBeWIR64:bvljs2o) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/07657e1d0e26ccd09b862e106e67c2707384dd6a/frontend/src/app/router.tsx#L84)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

let's rename this url and component to '/communication-preferences'
</blockquote></details>

Addressed.
___
*[`frontend/src/pages/dotmailerConsent/DotmailerConsent.tsx` line 33 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYs8lR43vDjLdfLW01w:-NYy29Yd4C2AHhVT9fND:b-flyjza) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/07657e1d0e26ccd09b862e106e67c2707384dd6a/frontend/src/pages/dotmailerConsent/DotmailerConsent.tsx#L33)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

don't restrict the width like this. it's not centred and notice how bad this looks on mobile because it's 60% of a small screen. Rather, restrict the max width of the page section. For example, "<Page.Section maxWidth='md' ...". FYI, the [maxWidth for all Containers is 'lg' by default](https://github.com/ocadotechnology/codeforlife-package-javascript/blob/8dc908c9c05be61bf0b0d222d91f966a45d89c28/src/theme/components/MuiContainer.ts#L5C14-L5C14).
</blockquote></details>

I can't restrict the max width of the Page section, if I do the grey won't take the whole width of the page. Can't I just make the field take up the whole width on xs?
___
*[`frontend/src/pages/studentsDashboard/joinSchool/JoinSchool.tsx` line 19 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYsQlq89GfLrStzEqp2:-NYy764l2jOjULbKbH-B:bvljs2o) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/07657e1d0e26ccd09b862e106e67c2707384dd6a/frontend/src/pages/studentsDashboard/joinSchool/JoinSchool.tsx#L19)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

no need to specify type <boolean>. it is inferred from the false.
</blockquote></details>

Addressed.
___
*[`frontend/src/pages/studentsDashboard/joinSchool/JoinSchool.tsx` line 66 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYsRCxDDl5QOSmBk_-x:-NYy7N4f4TbtPD7aIKCD:bvljs2o) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/07657e1d0e26ccd09b862e106e67c2707384dd6a/frontend/src/pages/studentsDashboard/joinSchool/JoinSchool.tsx#L66)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

A simpler approach to this is "<TextField sx={{ width: { xs: '100%', sm: '50%' } }} ..."
</blockquote></details>

Addressed.


<!-- Sent from Reviewable.io -->

2023-06-28 12:41 UTC, SKairinos reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48)* status: 45 of 52 files reviewed, 15 unresolved discussions (waiting on @faucomte97)

___
*[`frontend/src/features/header/user/Teacher.tsx` line 93 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYwaML_483Fziqy-ooS:-NZ0uNtIChckoK4oe5uP:b-791tq) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/010255df0dada57102e22901238acbe985e2358d/frontend/src/features/header/user/Teacher.tsx#L93)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

That's true but should we add it in?
</blockquote></details>

Will wait to see if Laura request this in the feedback
___
*[`frontend/src/features/header/MenuAccordion.tsx` line  at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYy-mco8ervLXJrZMFr:-NZ103Mv5bivKXKg8VIx:b-5ael0n) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/dfdf7474a655f3bfe4b7632c1ede0088ae2fa76e/frontend/src/features/header/MenuAccordion.tsx#L)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

I don't understand, Reviewable says this file and the following ones have been deleted?
</blockquote></details>

Yes, they were. I did some file reorganising to better abstract each component (see the files in header/summary and header/details). They original files are no longer relevant.
___
*[`frontend/src/pages/dotmailerConsent/DotmailerConsent.tsx` line 33 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-NYs8lR43vDjLdfLW01w:-NZ0vND80JTBkasTgOKi:b-1xavgp) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/07657e1d0e26ccd09b862e106e67c2707384dd6a/frontend/src/pages/dotmailerConsent/DotmailerConsent.tsx#L33)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

I can't restrict the max width of the Page section, if I do the grey won't take the whole width of the page. Can't I just make the field take up the whole width on xs?
</blockquote></details>

as discussed, set the maxWidth property of the Page.Section component


<!-- Sent from Reviewable.io -->

2023-06-28 14:03 UTC, faucomte97 reviewed
> Reviewed 1 of 34 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48)* status: 44 of 52 files reviewed, 12 unresolved discussions (waiting on @SKairinos)



<!-- Sent from Reviewable.io -->

2023-06-28 16:13 UTC, SKairinos reviewed
> Reviewed 1 of 13 files at r2, 2 of 2 files at r6, 2 of 3 files at r9, 4 of 4 files at r10, 3 of 3 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)



<!-- Sent from Reviewable.io -->

2023-06-28 16:28 UTC, faucomte97 reviewed
> Reviewed 6 of 13 files at r2, 2 of 2 files at r6, 1 of 3 files at r9, 4 of 4 files at r10, 3 of 3 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SKairinos)



<!-- Sent from Reviewable.io -->

2023-06-28 16:29 UTC, faucomte97 approved these changes
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SKairinos)



<!-- Sent from Reviewable.io -->

2023-06-28 16:29 UTC, faucomte97 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48#-:-NZ1pjs49w_vj9MR-fzH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SKairinos)



<!-- Sent from Reviewable.io -->

2023-06-28 16:59 UTC, SKairinos reviewed
> Reviewed 1 of 1 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SKairinos)



<!-- Sent from Reviewable.io -->

2023-06-28 17:00 UTC, SKairinos reviewed
> Reviewed 1 of 16 files at r1, 13 of 34 files at r3, 3 of 3 files at r5, 4 of 6 files at r7, 1 of 1 files at r8, 1 of 1 files at r14.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SKairinos)



<!-- Sent from Reviewable.io -->

2023-06-28 17:00 UTC, faucomte97 approved these changes
> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/48)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SKairinos)



<!-- Sent from Reviewable.io -->

2023-06-28 17:03 UTC, merged